In [1]:
import asyncio
import concurrent.futures
import functools
import pathlib
import multiprocessing
import os
import re
import time

from IPython.display import display, Markdown
import polars
from tqdm.notebook import tqdm

from utils import list_code

EVALUATION_DIR = pathlib.Path.cwd()
INPUT_PATH = EVALUATION_DIR / "output_dataset"

os.environ["INPUT_PATH"] = str(INPUT_PATH)

# Extract package data from PCAPs

TBD:
- **Parallel needs to be installed for this!**
- wireshark preferences:
  ```yaml
  dtls.psk: f28aa24f8cb8a7cc483cf336c0be70047f29
  tls.psk: f28aa24f8cb8a7cc483cf336c0be70047f29
  ```
  wireshark oscore_contexts:
  ```csv
  "01","64617461","f28aa24f8cb8a7cc483cf336c0be70047f29","","","AES-CCM-16-64-128 (CCM*)"
  "64617461","01","f28aa24f8cb8a7cc483cf336c0be70047f29","","","AES-CCM-16-64-128 (CCM*)"
  "02","646e73","0e08f702e6508657e3a0fd996a042531fc89","","","AES-CCM-16-64-128 (CCM*)"
  "646e73","02","0e08f702e6508657e3a0fd996a042531fc89","","","AES-CCM-16-64-128 (CCM*)"
  "03","70726f7879","b35c9719b3594553315a210b18720da0e750","","","AES-CCM-16-64-128 (CCM*)"
  "70726f7879","03","b35c9719b3594553315a210b18720da0e750","","","AES-CCM-16-64-128 (CCM*)"
  ```

In [2]:
list_code(EVALUATION_DIR / "extract_from_pcaps.sh")

#!/usr/bin/env bash
#
# extract_from_pcaps.sh
# Copyright (C) 2025 TU Dresden
#
# Distributed under terms of the MIT license.
#

SCRIPT_DIR=$( cd -- "$( dirname -- "$(realpath "$0")" )" &> /dev/null && pwd )
PROCS=$(grep -c '^processor' /proc/cpuinfo)
if [ $PROCS -gt 64 ]; then
    # leave some resources to collegues ;-)
    PROCS=$(( (PROCS * 3) / 4))
fi
OUTPUT_DATASET="${OUTPUT_DATASET:-${SCRIPT_DIR}/output_dataset}"


extract_from_pcap() {
    PCAP="$1"

    if ! echo "$PCAP" | grep -Eq ".*\.upstream.pcap" && ! [ -f "${PCAP%.pcap}".eth.csv ]; then
        "${SCRIPT_DIR}/extract_eth.sh" "${PCAP}" > "${PCAP%.pcap}".eth.csv
    elif [ -f "${PCAP%.pcap}".eth.csv ]; then
        echo "\"${PCAP%.pcap}.eth.csv\" exists already" >&2
    fi
    if echo "${PCAP}" | grep -Eq "\<https-" && ! echo "$PCAP" | grep -Eq ".*\.upstream.pcap" && ! [ -f "${PCAP%.pcap}".http.csv ]; then
        "${SCRIPT_DIR}/extract_http.sh" "${PCAP}" > "${PCAP%.pcap}".http.csv
    elif echo "${PCAP}" | grep -Eq -e "-schc-" && ! echo "$PCAP" | grep -Eq ".*\.upstream.pcap" && ! [ -f "${PCAP%.pcap}".coap.csv ]; then
        if echo "$PCAP" | grep -q "oscore"; then
            OSCORE="oscore"
        fi
        "${SCRIPT_DIR}/extract_schc.py" "${PCAP%.pcap}".eth.csv | \
             text2pcap -l 101 -t "%s.%f" -q - - 2>/dev/null | \
             "${SCRIPT_DIR}/extract_coap.sh" - "${OSCORE}" > "${PCAP%.pcap}".coap.csv
    elif ! echo "${PCAP}" | grep -Eq "\<https-" && ! [ -f "${PCAP%.pcap}".coap.csv ]; then
        "${SCRIPT_DIR}/extract_coap.sh" "${PCAP}" > "${PCAP%.pcap}".coap.csv
    elif [ -f "${PCAP%.pcap}".http.csv ]; then
        echo "\"${PCAP%.pcap}.http.csv\" exists already" >&2
    elif [ -f "${PCAP%.pcap}".coap.csv ]; then
        echo "\"${PCAP%.pcap}.coap.csv\" exists already" >&2
    fi
}

export -f extract_from_pcap
export SCRIPT_DIR

find "${OUTPUT_DATASET}" -name "*.wpan.pcap" -o -name "*.upstream.pcap" | \
    parallel -j"${PROCS}" extract_from_pcap

In [3]:
list_code(EVALUATION_DIR / "extract_eth.sh")

#! /bin/sh
#
# extract_eth.sh
# Copyright (C) 2025 TU Dresden
#
# Distributed under terms of the MIT license.
#

if [ $# -ne 1 ]; then
    echo "usage: $0 <pcap file>" >&2
    exit 1
fi

PCAP="$1"

FIELDS="frame.number frame.time_epoch eth.src eth.dst eth.type eth.payload"
echo "${FIELDS}" | \
    awk 'BEGIN {OFS="\t"} { for (i = 1; i <= NF; i++) { printf "%s%s", $i, (i < NF) ? OFS : ORS } }'
tshark -Tfields -e frame.number -e frame.time_epoch -e eth.src -e eth.dst -e eth.type -e data --disable-protocol ALL --enable-protocol eth -r "${PCAP}"

In [4]:
list_code(EVALUATION_DIR / "extract_schc.py")

#! /usr/bin/env python3
# vim:fenc=utf-8
#
# Copyright (C) 2025 TU Dresden
#
# Distributed under terms of the MIT license.

import argparse
import binascii
import csv
import datetime
import io
import pathlib
import re
import sys
import unittest.mock


from scenarios.schc.schc import OpenSCHCLoader


SCRIPT_PATH = pathlib.Path(__file__).resolve().parent
OPENSCHC_PATH = SCRIPT_PATH / "scenarios" / "schc" / "openschc" / "src"
ETH_COL_TYPES = {
    "frame.number": int,
    "eth.src": lambda x: bytes.fromhex(x.replace(":", "")),
    "eth.dst": lambda x: bytes.fromhex(x.replace(":", "")),
    "eth.type": lambda x: int(x[2:], base=16),
    "eth.payload": bytes.fromhex,
}
ROUTE_COL_TYPES = {
    "eth": bytes.fromhex,
}


def convert_columns(row, conversion_map):
    for col in conversion_map:
        row[col] = conversion_map[col](row[col])


def get_device_table(csvpath):
    routes_path = csvpath.parent / csvpath.name.replace(".wpan.eth.csv", ".routes.txt")
    device_table = {}
    with routes_path.open() as routes_file:
        reader = csv.DictReader(
            routes_file,
            delimiter=" ",
            fieldnames=["name", "ipv6", "eth"]
        )
        for row in reader:
            convert_columns(row, ROUTE_COL_TYPES)
            device_table[row["eth"]] = row["name"]
    return device_table


def get_rules(csvpath, device_table):
    schc_path = csvpath.parent / ".." / "scenarios" / "schc"
    rule_name = re.sub(r"^(.+-schc-[dp][12]).*", r"\1", csvpath.name)
    rule_mode = re.sub(r"^.+-schc-[dp][12](-([^_]+))?_.*", r"\2", csvpath.name)

    rev_device_table = {v: k for k, v in device_table.items()}

    if rule_mode == "min-rules":
        rules_paths = {
            rev_device_table["client"]: schc_path / f"{rule_name}-rules-min.json"
        }
    elif rule_mode == "peer-based":
        rules_paths = {}
        for rules in schc_path.glob(f"{rule_name}-rules-*.json"):
            if rules.name.endswith("-min.json"):
                continue
            else:
                host = re.sub(r".*-rules-(.*)\.json", r"\1", rules.name)
                host_addr = rev_device_table[host]
                client_addr = rev_device_table["client"]
                rules_paths[
                    bytes(a ^ b for a, b in zip(host_addr, client_addr))
                ] = rules
    else:
        rules_paths = {
            rev_device_table["client"]: schc_path / f"{rule_name}-rules.json"
        }

    for rules in rules_paths.values():
        assert rules.exists(), f"{rules} does not exist"
    return rules_paths



class DevNull:
    def __enter__(self):
        self._stdout = sys.stdout
        self._stderr = sys.stderr
        sys.stdout = io.StringIO()
        sys.stderr = io.StringIO()
        return self

    def __exit__(self, *args):
        del sys.stdout
        del sys.stderr
        sys.stdout = self._stdout
        sys.stderr = self._stderr


def dump_pkt(pkt):
    chunk_size = 16
    for i in range(0, len(pkt), chunk_size):
        chunk = pkt[i:i+chunk_size]
        print(f"{i:06x}", binascii.hexlify(chunk, " ").decode())
    print(f"{len(pkt):06x}")


def read_csv(csvfile, device_table, rules):
    reader = csv.DictReader(csvfile, delimiter="\t")
    openschc_loader = OpenSCHCLoader(OPENSCHC_PATH)

    rule_manager = openschc_loader.get_rule_manager()
    for device_id, rules_file in rules.items():
        rule_manager.Add(device=device_id, file=str(rules_file))
    peer_based = len(rules) > 1
    protocol = {}
    for key in device_table:
        protocol[key] = openschc_loader.get_protocol(
            layer2=unittest.mock.MagicMock(),
            system=unittest.mock.MagicMock(),
            role="device" if device_table[key] == "client" else "core",
        )
        protocol[key].set_rulemanager(rule_manager)
    fragment_rows = {k: [] for k in device_table}
    prev_frame_num = 0
    for i, row in enumerate(reader):
        convert_columns(row, ETH_COL_TYPES)

        assert row["frame.number"] == prev_frame_num + 1, (
            f"Unexpected frame number: {row['frame.number']} != {prev_frame_num + 1}"
        )
        prev_frame_num = row["frame.number"]
        if row["eth.type"] != 0x88b5:
            print(row["frame.time_epoch"])
            dump_pkt(row["eth.payload"])
            continue

        src = row["eth.src"]
        dst = row["eth.dst"]
        from_device = device_table[src] == "client"
        if from_device:
            kwargs = {"device_id": src, "core_id": dst}
        else:
            kwargs = {"device_id": dst, "core_id": src}
        if peer_based:
            kwargs["device_id"] = bytes(a ^ b for a, b in zip(src, dst))

        with DevNull():
            device_id, pkt = protocol[dst].schc_recv(row["eth.payload"], **kwargs)

        assert device_id

        if pkt is None:
            fragment_rows[dst].append((i, row))
        else:
            pkt = bytes(pkt)
            for j, fragment_row in fragment_rows[dst]:
                print(fragment_row["frame.time_epoch"])
                dump_pkt(pkt)
            print(row["frame.time_epoch"])
            dump_pkt(pkt)
            del fragment_rows[dst][:]
        protocol[dst].layer2.reset_mock()
        protocol[dst].system.reset_mock()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "eth_csv",
        help="A CSV containing SCHC encoded Ethernet payloads"
        r"with the following columns separated by tabs (`\t`). "
        "frame.number: The frame number from the original PCAP, "
        "frame.time_epoch: The time since UNIX epoch from the original PCAP, "
        "eth.src: The Ethernet source address in hexadecimal, "
        "eth.dst: The Ethernet destination address in hexadecimal, "
        "eth.type: The Ethertype used to mark SCHC frames in hexadecimal `0x` notation, "
        "eth.payload: The payload of the Ethernet frame in hexadecimal",
        type=pathlib.Path)
    args = parser.parse_args()

    device_table = get_device_table(args.eth_csv)
    rules = get_rules(args.eth_csv, device_table)
    with args.eth_csv.open() as csvfile:
        read_csv(csvfile, device_table, rules)


if __name__ == "__main__":
    main()

In [5]:
list_code(EVALUATION_DIR / "extract_coap.sh")

#! /bin/sh
#
# extract_coap.sh
# Copyright (C) 2025 TU Dresden
#
# Distributed under terms of the MIT license.
#

if [ $# -ne 1 ] && [ $# -ne 2 ]; then
    echo "usage: $0 <pcap file|-> [oscore]" >&2
    exit 1
fi

PCAP="$1"

FIELDS="frame.number frame.time_epoch frame.protocols dtls.record.content_type"
FIELDS="${FIELDS} coap.code coap.request_first_in coap.mid coap.token coap.opt.ctype coap.opt.block_number coap.opt.block_mflag coap.opt.block_size coap.block coap.block.reassembled.in"

if echo "$PCAP" | grep -q "oscore" || [ "$2" = "oscore" ]; then
    FIELDS="${FIELDS} oscore.code oscore.opt.ctype oscore.opt.block_number oscore.opt.block_mflag oscore.opt.block_size"
fi


echo "${FIELDS}" | \
    awk 'BEGIN {OFS="\t"} { for (i = 1; i <= NF; i++) { printf "%s%s", $i, (i < NF) ? OFS : ORS } }'
tshark -Tfields $(for field in ${FIELDS}; do printf -- "-e %s " "${field}"; done) -r "${PCAP}"

In [6]:
!hyperfine --warmup 0 --max-runs 1 --show-output --ignore-failure "{EVALUATION_DIR}"/extract_from_pcaps.sh

Benchmark 1: ./extract_from_pcaps.sh
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-d1_cbor_dns_message_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-d1_cbor_dns_message_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-d1_json_dns_message_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-d1_json_dns_message_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-d2_cbor_dns_message_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-d2_cbor_dns_message_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-base-d1_cbor_dns_message_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-base-d1_cbor_dns_message_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-d2_json_dns_message_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-d2_json_dns_message_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/https-d2_json_dns_cbor.wpan.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/https-d2_json_dns_cbor.wpan.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/https-d2_json_dns_message.wpan.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/https-d2_json_dns_message.wpan.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-p1_cbor_dns_message_b64.upstream.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-p1_json_dns_message_b64.upstream.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-base-d1_json_dns_message_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-base-d1_json_dns_message_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-base-d2_cbor_dns_message_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-base-d2_cbor_dns_message_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-p2_cbor_dns_message_b64.upstream.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-base-p1_cbor_dns_cbor_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-base-p1_cbor_dns_cbor_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-base-d2_json_dns_message_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-base-d2_json_dns_message_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-base-p1_json_dns_message_b64.upstream.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-p2_json_dns_message_b64.upstream.pcap" appears to have been cut short in the middle of a packet.
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-schc-d1_cbor_dns_cbor_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-base-schc-d1_cbor_dns_cbor_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-schc-d1_json_dns_message_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-schc-d2-min-rules_cbor_dns_cbor_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-base-schc-d1_json_dns_message_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-base-schc-d2-min-rules_cbor_dns_cbor_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-schc-d2-peer-based_cbor_dns_cbor_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-base-schc-d2-peer-based_cbor_dns_cbor_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-schc-d2_cbor_dns_cbor_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-schc-p1_cbor_dns_message_b64.upstream.pcap" appears to have been cut short in the middle of a packet.
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
tshark: The file "/home/service/pivot-eval-tbd/data/coaps-schc-p2_json_dns_cbor_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-base-schc-d2_cbor_dns_cbor_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-schc-p1_json_dns_message_b64.upstream.pcap" appears to have been cut short in the middle of a packet.
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-schc-p1_cbor_dns_message.wpan.pcap" appears to have been cut short in the middle of a packet.
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-base-schc-d2-peer-based_json_dns_message_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-base-schc-p1_json_dns_message_b64.upstream.pcap" appears to have been cut short in the middle of a packet.
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-schc-p2_cbor_dns_message_b64.upstream.pcap" appears to have been cut short in the middle of a packet.
tshark: The file "/home/service/pivot-eval-tbd/data/oscore-schc-d2_json_dns_message_b64.wpan.pcap" appears to have been cut short in the middle of a packet.
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored
  warnings.warn("Note: T_COAP_OPT_END is ignored")
/home/service/pivot-eval-tbd/scenarios/schc/openschc/src/gen_rulemanager.py:593: UserWarning: Note: T_COAP_OPT_END is ignored

# Generate Training Data

In [7]:
schema_overrides = {
    "coap": {
        "coap.token": str,
        "coap.opt.block_number": str,
        "coap.opt.block_mflag": str,
        "coap.opt.block_size": str,
        "oscore.opt.block_number": str,
        "oscore.opt.block_mflag": str,
        "oscore.opt.block_size": str,
    },
    "coap_upstream": {
        "coap.token": str,
        "coap.opt.block_number": str,
        "coap.opt.block_mflag": str,
        "coap.opt.block_size": str,
        "oscore.opt.block_number": str,
        "oscore.opt.block_mflag": str,
        "oscore.opt.block_size": str,
    },
}

In [8]:
COLUMN_ORDER = {
    "coap": [
        "client.coap.response.recv_time_epoch",
        "client.type",
        "client.dns.qry.name",
        "client.dns.qry.type",
        "client.coap.url",
        "client.coap.media_type",
        "client.coap.response.code",
        "client.coap.response.payload",
        "frame.number",
        "frame.time_epoch",
        "frame.protocols",
        "eth.src",
        "eth.dst",
        "eth.type",
        "eth.payload",
        "ipv6.prefix",
        "dtls.record.content_type",
        "coap.is_response",
        "coap.code",
        "coap.request_first_in",
        "coap.mid",
        "coap.token",
        "coap.opt.ctype",
        "coap.block",
        "coap.block.reassembled.in",
        "coap.opt.block_number",
        "coap.opt.block_mflag",
        "coap.opt.block_size",
        "oscore.code",
        "oscore.opt.ctype",
        "oscore.opt.block_number",
        "oscore.opt.block_mflag",
        "oscore.opt.block_size",
        "upstream.frame.number",
        "upstream.frame.time_epoch",
        "upstream.frame.protocols",
        "upstream.ipv6.prefix",
        "upstream.dtls.record.content_type",
        "upstream.coap.code",
        "upstream.coap.request_first_in",
        "upstream.coap.mid",
        "upstream.coap.token",
        "upstream.coap.opt.ctype",
        "upstream.coap.block",
        "upstream.coap.block.reassembled.in",
        "upstream.coap.opt.block_number",
        "upstream.coap.opt.block_mflag",
        "upstream.coap.opt.block_size",
        "upstream.oscore.code",
        "upstream.oscore.opt.ctype",
        "upstream.oscore.opt.block_number",
        "upstream.oscore.opt.block_mflag",
        "upstream.oscore.opt.block_size",
    ],
    "http": [
        "client.http.response.recv_time_epoch",
        "client.type",
        "client.dns.qry.name",
        "client.dns.qry.type",
        "client.http.url",
        "client.http.media_type",
        "client.http.response.status",
        "client.http.response.payload",
        "frame.number",
        "frame.time_epoch",
        "frame.protocols",
        "eth.src",
        "eth.dst",
        "eth.type",
        "eth.payload",
        "ipv6.prefix",
        "tls.record.content_type",
        "tcp.analysis.acks_frame",
        "tcp.analysis.duplicate_ack_frame",
        "tcp.analysis.rto_frame",
        "tcp.reassembled_in",
        "tcp.segment",
        "http2.headers.method",
        "http2.streamid",
        "http2.request_in",
        "http2.body.reassembled.in",
        "http2.headers.content_type",
        "upstream.ipv6.prefix",
    ],
}

WORKERS = multiprocessing.cpu_count() // 2


scenario_files = {}

print(f"Start {time.time()}")

for root, dirs, files in INPUT_PATH.walk():
    for file in files:
        if match := re.search(
            r".*\.((wpan|upstream)\.(coap|http|eth)\.csv|(client|proxy)\.log)",
            file,
        ):
            scenario = file.split(".")[0]
            if scenario not in scenario_files:
                scenario_files[scenario] = []
            if not (
                file.startswith("oscore")
                or file.startswith("coaps-p")
                or file.startswith("coaps-schc-p")
                or file.startswith("coap-p")
                or file.startswith("https")
            ) and (
                match[1] == "upstream"
                or match[4] == "proxy"
            ):
                display(Markdown(f"## No upstream {scenario}"))
                continue
            elif match[1] == "client.log":
                table = "client"
            elif match[1] == "proxy.log":
                table = "proxy"
            else:
                table = match[3]
            if match[2] == "upstream":
                table = f"{table}_upstream"
            scenario_files[scenario].append(
                {
                    "table": table,
                    "path": root / file,
                }
            )


def split_stream_ids(stream_id):
    if stream_id is None:
        return stream_id
    stream_id = [int(s) for s in stream_id.split(",")]
    if all(x == 0 for x in stream_id):
        return 0
    while any(x == 0 for x in stream_id):
        stream_id.remove(0)
    assert all(x == stream_id[0] for x in stream_id), stream_id
    return stream_id[0]


def merge_tables(scenario, scenario_files):
    if (INPUT_PATH / f"{scenario}.merged.csv.gz").exists() or \
       (INPUT_PATH / f"{scenario}.training.csv.gz").exists():
        return
    tables = {}
    for file in scenario_files:
        table = file["table"]
        path = file["path"]
        tables[table] = polars.read_csv(
            path,
            separator="\t",
            schema_overrides=schema_overrides.get(table)
        )
    if scenario.startswith("https"):
        assert all(table in tables for table in ["client", "eth", "http"]), (
            f"{', '.join(table for table in ["client", "eth", "http"] if table not in tables)} missing from {scenario}"
        )
        app_protocol = "http"
        wpan_column = "http2.streamid"
        client_column = "stream_id"
        code = "status"
        
        tables["http"] = tables["http"].with_columns(
            polars.col("http2.streamid")
            .map_elements(split_stream_ids, return_dtype=polars.Int64)
            .alias("http2.streamid")
        )
    else:
        assert all(table in tables for table in ["client", "eth", "coap"]), (
            f"{', '.join(table for table in ["client", "eth", "coap"] if table not in tables)} missing from {scenario}"
        )
        assert "coap_upstream" not in tables or "proxy" in tables, (
            f"proxy missing from {scenario}"
        )
        app_protocol = "coap"
        wpan_column = "coap.token"
        client_column = "token"
        code = "code"
    df = tables["eth"].join(
        tables[app_protocol][
            [
                col for col in tables[app_protocol].columns
                if col != "frame.time_epoch"
            ]
        ],
        on="frame.number",
        how="inner"
    )
    if "coap_upstream" in tables:
        df = df.with_columns(((df["coap.code"] & (7 << 5)) != 0).alias("coap.is_response"))
        upstream_df = tables["coap_upstream"]
        upstream_df = upstream_df.with_columns(((upstream_df["coap.code"] & (7 << 5)) != 0).alias("coap.is_response"))
        df = df.join(
            tables["proxy"],
            left_on="coap.token",
            right_on="old_token",
            how="left",
        )
        df = df.join(
            upstream_df,
            left_on=["coap.is_response", "new_token"],
            right_on=["coap.is_response", "coap.token"],
            how="left",
            suffix=".upstream",
        )
        df = df.rename({"new_token": "coap.token.upstream"}).join(
            tables["client"],
            left_on="coap.token.upstream",
            right_on="token",
        ).rename(
            lambda c: f"upstream.{c[:-9]}" if c.endswith(".upstream") else c
        ).rename(
            {
                "timestamp": "client.coap.response.recv_time_epoch",
                "wpan_prefix": "ipv6.prefix",
                "upstream_prefix": "upstream.ipv6.prefix",
                "type": "client.type",
                "query_name": "client.dns.qry.name",
                "query_type": "client.dns.qry.type",
                "url": "client.coap.url",
                "media_type": "client.coap.media_type",
                "response_code": "client.coap.response.code",
                "response_payload": "client.coap.response.payload",
            }
        )
    else:
        df = df.join(
            tables["client"],
            left_on=wpan_column,
            right_on=client_column,
        ).rename(
            {
                "timestamp": f"client.{app_protocol}.response.recv_time_epoch",
                "wpan_prefix": "ipv6.prefix",
                "upstream_prefix": "upstream.ipv6.prefix",
                "type": "client.type",
                "query_name": "client.dns.qry.name",
                "query_type": "client.dns.qry.type",
                "url": f"client.{app_protocol}.url",
                "media_type": f"client.{app_protocol}.media_type",
                f"response_{code}": f"client.{app_protocol}.response.{code}",
                "response_payload": f"client.{app_protocol}.response.payload",
            }
        )
    
    for k in list(tables):
        del tables[k]
    del tables
    assert all(c in COLUMN_ORDER[app_protocol] for c in df.columns), (
        f"{', '.join(c for c in df.columns if c not in COLUMN_ORDER[app_protocol])} of {scenario} not in column order"
    )
    df = df.select([c for c in COLUMN_ORDER[app_protocol] if c in df.columns])
    max_len = df["eth.payload"].str.len_chars().max()
    if max_len is None:
        print(f"Skipping {scenario}")
        display(df)
        return
    df.to_pandas().to_csv(
        INPUT_PATH / f"{scenario}.merged.csv.gz",
        compression={"method": "gzip", "compresslevel": 9},
    )
    df_training = df.select(
        ["frame.number", "frame.time_epoch", "client.type", "eth.payload"]
        # add upstream mid and token to ensure only duplicate frames
        # due to upstream retransmissions are deleted
        + (["upstream.coap.mid", "upstream.coap.token"] if "upstream.coap.mid" in df.columns else [])
    ).with_columns(
        **{
            "eth.payload": polars.col("eth.payload").str.pad_end(max_len, "x")
        }
    )
    del df
    # deduplicate frames that were duplicated due to upstream retransmission
    df_training.unique(keep="last", maintain_order=True).select(
        ["frame.number", "frame.time_epoch", "client.type", "eth.payload"]
    ).to_pandas().to_csv(
        INPUT_PATH / f"{scenario}.training.csv.gz",
        compression={"method": "gzip", "compresslevel": 9},
    )
    del df_training

print(f"Running on {WORKERS} workers")
with concurrent.futures.ProcessPoolExecutor(max_workers=WORKERS) as executor:
    def _merge_tables(scenario_name):
        return merge_tables(scenario_name, scenario_files[scenario_name])
    
    for _ in tqdm(
        executor.map(
            _merge_tables,
            scenario_files.keys(),
        ),
        total=len(scenario_files),
    ):
        continue

print(f"Stop {time.time()}")

Start 1750800035.8364289
Running on 12 workers

  0%|          | 0/296 [00:00<?, ?it/s]

Stop 1750801910.8248036

# Check If Files are Complete

In [9]:
for root, dirs, files in INPUT_PATH.walk():
    for file in files:
        match = re.search(r".*\.training\.csv\.gz$", file)
        if not match:
            continue
        if file.startswith("https-"):
            df = polars.read_csv(
                root / file.replace("training.csv.gz", "wpan.http.csv"),
                separator="\t",
            )
            # TLS control packages (e.g. handshake) should be excluded
            non_app_frames = set(
                df.filter(
                    (df["tls.record.content_type"] != 23) | (df["tls.record.content_type"].is_null())
                )["frame.number"].to_list()
            )
            # pure control packages (e.g. SYN/ACK) should be excluded
            non_app_frames |= set(
                df.filter(
                    df["frame.protocols"].str.ends_with(":tcp")
                )["frame.number"].to_list()
            )
            non_app_frames |= set(
                df.filter(
                    df["http2.streamid"].str.split(",").list.eval(
                        polars.element() == "0"
                    ).list.all()
                )["frame.number"].to_list()
            )
        else:
            df = polars.read_csv(
                root / file.replace("training.csv.gz", "wpan.coap.csv"),
                separator="\t",
                schema_overrides=schema_overrides["coap"],
            )
            if file.startswith("coaps"):
                # DTLS control packages (e.g. handshake) should be excluded
                non_app_frames = set(
                    df.filter(
                        df["frame.protocols"].str.ends_with(":dtls")
                    )["frame.number"].to_list()
                )
            else:
                non_app_frames = set()
            # Empty CoAP ACKs should be excluded
            non_app_frames |= set(
                df.filter(
                    df["coap.code"] == 0
                )["frame.number"].to_list()
            )
        del df
        df = polars.read_csv(root / file, separator=",")
        exp_frames = polars.DataFrame(
            {"frame.exp": [i for i in range(1, df["frame.number"].max() + 1) if i not in non_app_frames]}
        )
        if (df.is_empty() or df.shape[0] != exp_frames.shape[0]):
            display(Markdown(f"## ❌ Error in {file}"))
            display(Markdown(f"Number of Non-App frames {len(non_app_frames)}"))
            display(Markdown("### Broken table"))
            display(df)
            display(Markdown(f"### Duplicate frame numbers"))
            display(df.filter(polars.count("frame.number").over(df.columns) > 1))
            display(Markdown(f"### Expected App frames [{df.shape[0] - len(non_app_frames)}]"))
            display(exp_frames)
            display(Markdown(f"### Different frame numbers"))
            display(
                polars.DataFrame(
                    {
                        "diff": sorted(
                            set(df["frame.number"].to_list()).difference(
                                set(exp_frames["frame.exp"].to_list()),
                            ) | 
                            set(exp_frames["frame.exp"].to_list()).difference(
                                set(df["frame.number"].to_list()),
                            )
                        )
                    }
                )
            )
            display(Markdown("### Non-App frames"))
            display(df.filter(df["frame.number"].is_in(non_app_frames)))
            display(polars.DataFrame({"non_app_frames": sorted(non_app_frames)}))
            merged = file.replace("training.csv.gz", "merged.csv.gz")
            display(Markdown(f"### [{merged}]({(root / merged).relative_to(EVALUATION_DIR)})"))
            merged_df = polars.read_csv(root / merged, separator=",")
            display(merged_df)
            if file.startswith("https-"):
                wpan_http = file.replace("training.csv.gz", "wpan.http.csv")
                display(Markdown(f"### [{wpan_http}]({(root / wpan_http).relative_to(EVALUATION_DIR)})"))
                display(polars.read_csv(root / wpan_http, separator="\t"))
            else:
                wpan_coap = file.replace("training.csv.gz", "wpan.coap.csv")
                display(Markdown(f"### [{wpan_coap}]({(root / wpan_coap).relative_to(EVALUATION_DIR)})"))
                display(polars.read_csv(root / wpan_coap, separator="\t"))
            continue
        df = df.with_columns(exp_frames)
        check = df["frame.number"] != df["frame.exp"]
        if check.any():
            display(Markdown("### Different from expected"))
            stored = file.replace(".training.csv.gz", ".training_broken.csv")
            display(Markdown(f"#### [{stored}]({(root / stored).relative_to(EVALUATION_DIR)})"))
            display(df.filter(check))
            df.write_csv(root / stored)
            break
        display(Markdown(f"## ✅ {file} OK"))
        del df

## ✅ coaps-d2_cbor_dns_cbor.training.csv.gz OK

## ✅ coaps-d1_cbor_dns_cbor.training.csv.gz OK

## ✅ coaps-d1_json_dns_cbor.training.csv.gz OK

## ✅ coaps-d1_cbor_dns_message.training.csv.gz OK

## ✅ coaps-d2_cbor_dns_message.training.csv.gz OK

## ✅ coaps-d1_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ coaps-d2_json_dns_cbor.training.csv.gz OK

## ✅ coaps-d2_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ coaps-d1_json_dns_cbor_b64.training.csv.gz OK

## ✅ coaps-d2_json_dns_cbor_b64.training.csv.gz OK

## ✅ coaps-p1_cbor_dns_cbor.training.csv.gz OK

## ✅ coaps-d2_cbor_dns_message_b64.training.csv.gz OK

## ✅ coaps-d1_cbor_dns_message_b64.training.csv.gz OK

## ✅ coaps-d1_json_dns_message_b64.training.csv.gz OK

## ✅ coaps-p1_cbor_dns_message.training.csv.gz OK

## ✅ coaps-p1_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ coaps-p1_json_dns_cbor.training.csv.gz OK

## ✅ coaps-d2_json_dns_message_b64.training.csv.gz OK

## ✅ coaps-p1_cbor_dns_message_b64.training.csv.gz OK

## ✅ coaps-d1_json_dns_message.training.csv.gz OK

## ✅ coaps-p2_cbor_dns_cbor.training.csv.gz OK

## ✅ coaps-p2_cbor_dns_message.training.csv.gz OK

## ✅ coaps-p1_json_dns_cbor_b64.training.csv.gz OK

## ✅ coaps-p2_json_dns_cbor.training.csv.gz OK

## ✅ https-p1_cbor_dns_cbor.training.csv.gz OK

## ✅ coaps-p2_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ coap-d1_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ coaps-d2_json_dns_message.training.csv.gz OK

## ✅ coaps-p1_json_dns_message_b64.training.csv.gz OK

## ✅ coaps-p1_json_dns_message.training.csv.gz OK

## ✅ coap-d1_cbor_dns_message_b64.training.csv.gz OK

## ✅ coaps-p2_cbor_dns_message_b64.training.csv.gz OK

## ✅ coap-d1_json_dns_cbor_b64.training.csv.gz OK

## ✅ https-p1_json_dns_cbor.training.csv.gz OK

## ✅ coaps-p2_json_dns_message.training.csv.gz OK

## ✅ oscore-d1_cbor_dns_cbor.training.csv.gz OK

## ✅ coaps-p2_json_dns_cbor_b64.training.csv.gz OK

## ✅ coap-d1_json_dns_message_b64.training.csv.gz OK

## ✅ oscore-d1_cbor_dns_message.training.csv.gz OK

## ✅ coap-d1_cbor_dns_cbor.training.csv.gz OK

## ✅ oscore-base-d2_json_dns_message_b64.training.csv.gz OK

## ✅ coap-d2_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ coaps-p2_json_dns_message_b64.training.csv.gz OK

## ✅ oscore-d1_json_dns_message.training.csv.gz OK

## ✅ coaps-schc-d1_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-d2_cbor_dns_cbor.training.csv.gz OK

## ✅ coap-d2_cbor_dns_message_b64.training.csv.gz OK

## ✅ oscore-d2_cbor_dns_message.training.csv.gz OK

## ✅ coap-d2_json_dns_cbor_b64.training.csv.gz OK

## ✅ coap-d1_cbor_dns_message.training.csv.gz OK

## ✅ oscore-base-d2_json_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-d2_json_dns_message.training.csv.gz OK

## ✅ oscore-base-d1_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-p1_cbor_dns_cbor.training.csv.gz OK

## ✅ oscore-p1_cbor_dns_message.training.csv.gz OK

## ✅ coap-p1_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ coap-d1_json_dns_cbor.training.csv.gz OK

## ✅ coap-d2_json_dns_message_b64.training.csv.gz OK

## ✅ coaps-schc-d1_cbor_dns_message_b64.training.csv.gz OK

## ✅ coap-d2_cbor_dns_cbor.training.csv.gz OK

## ✅ oscore-base-d1_cbor_dns_message_b64.training.csv.gz OK

## ✅ coap-p1_cbor_dns_message_b64.training.csv.gz OK

## ✅ oscore-p2_cbor_dns_cbor.training.csv.gz OK

## ✅ oscore-p1_json_dns_message.training.csv.gz OK

## ✅ coaps-schc-d1_json_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-base-d1_json_dns_cbor_b64.training.csv.gz OK

## ❌ Error in https-p2_cbor_dns_cbor.training.csv.gz

Number of Non-App frames 215702

### Broken table

shape: (419_112, 5)
┌────────┬──────────────┬──────────────────┬─────────────┬─────────────────────────────────┐
│        ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload                     │
│ ---    ┆ ---          ┆ ---              ┆ ---         ┆ ---                             │
│ i64    ┆ i64          ┆ f64              ┆ str         ┆ str                             │
╞════════╪══════════════╪══════════════════╪═════════════╪═════════════════════════════════╡
│ 0      ┆ 12           ┆ 1.7507e9         ┆ dns         ┆ 6000000000a50640fdd87b12eccc00… │
│ 1      ┆ 12           ┆ 1.7507e9         ┆ data        ┆ 6000000000a50640fdd87b12eccc00… │
│ 2      ┆ 14           ┆ 1.7507e9         ┆ dns         ┆ 6000000000850640fdd87b12eccc00… │
│ 3      ┆ 14           ┆ 1.7507e9         ┆ data        ┆ 6000000000850640fdd87b12eccc00… │
│ 4      ┆ 15           ┆ 1.7507e9         ┆ dns         ┆ 6000000000650640fdd87b12eccc00… │
│ …      ┆ …            ┆ …                ┆ …           ┆ …                               │
│ 419107 ┆ 318966       ┆ 1.7507e9         ┆ data        ┆ 6000000000950640fdd87b12eccc00… │
│ 419108 ┆ 318967       ┆ 1.7507e9         ┆ dns         ┆ 6000000000650640fdd87b12eccc00… │
│ 419109 ┆ 318967       ┆ 1.7507e9         ┆ data        ┆ 6000000000650640fdd87b12eccc00… │
│ 419110 ┆ 318969       ┆ 1.7507e9         ┆ dns         ┆ 6000000000e50640fdd87b12eccc00… │
│ 419111 ┆ 318969       ┆ 1.7507e9         ┆ data        ┆ 6000000000e50640fdd87b12eccc00… │
└────────┴──────────────┴──────────────────┴─────────────┴─────────────────────────────────┘

### Duplicate frame numbers

shape: (0, 5)
┌─────┬──────────────┬──────────────────┬─────────────┬─────────────┐
│     ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload │
│ --- ┆ ---          ┆ ---              ┆ ---         ┆ ---         │
│ i64 ┆ i64          ┆ f64              ┆ str         ┆ str         │
╞═════╪══════════════╪══════════════════╪═════════════╪═════════════╡
└─────┴──────────────┴──────────────────┴─────────────┴─────────────┘

### Expected App frames [203410]

shape: (209_556, 1)
┌───────────┐
│ frame.exp │
│ ---       │
│ i64       │
╞═══════════╡
│ 12        │
│ 14        │
│ 15        │
│ 19        │
│ 20        │
│ …         │
│ 318963    │
│ 318965    │
│ 318966    │
│ 318967    │
│ 318969    │
└───────────┘

### Different frame numbers

shape: (0, 1)
┌──────┐
│ diff │
│ ---  │
│ null │
╞══════╡
└──────┘

### Non-App frames

shape: (0, 5)
┌─────┬──────────────┬──────────────────┬─────────────┬─────────────┐
│     ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload │
│ --- ┆ ---          ┆ ---              ┆ ---         ┆ ---         │
│ i64 ┆ i64          ┆ f64              ┆ str         ┆ str         │
╞═════╪══════════════╪══════════════════╪═════════════╪═════════════╡
└─────┴──────────────┴──────────────────┴─────────────┴─────────────┘

shape: (215_702, 1)
┌────────────────┐
│ non_app_frames │
│ ---            │
│ i64            │
╞════════════════╡
│ 1              │
│ 2              │
│ 3              │
│ 4              │
│ 5              │
│ …              │
│ 631359         │
│ 631361         │
│ 631365         │
│ 631367         │
│ 631368         │
└────────────────┘

### [https-p2_cbor_dns_cbor.merged.csv.gz](data/https-p2_cbor_dns_cbor.merged.csv.gz)

shape: (419_112, 29)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│        ┆ client.htt ┆ client.typ ┆ client.dn ┆ … ┆ http2.req ┆ http2.bod ┆ http2.hea ┆ upstream. │
│ ---    ┆ p.response ┆ e          ┆ s.qry.nam ┆   ┆ uest_in   ┆ y.reassem ┆ ders.cont ┆ ipv6.pref │
│ i64    ┆ .recv_time ┆ ---        ┆ e         ┆   ┆ ---       ┆ bled.in   ┆ ent_type  ┆ ix        │
│        ┆ …          ┆ str        ┆ ---       ┆   ┆ f64       ┆ ---       ┆ ---       ┆ ---       │
│        ┆ ---        ┆            ┆ str       ┆   ┆           ┆ str       ┆ str       ┆ str       │
│        ┆ f64        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0      ┆ 1.7507e9   ┆ dns        ┆ mc.yandex ┆ … ┆ null      ┆ null      ┆ applicati ┆ fdd8:7b12 │
│        ┆            ┆            ┆ .com.     ┆   ┆           ┆           ┆ on/dns+cb ┆ :ecc0::   │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ or        ┆           │
│ 1      ┆ 1.7507e9   ┆ data       ┆ null      ┆ … ┆ null      ┆ null      ┆ applicati ┆ fdd8:7b12 │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ on/dns+cb ┆ :ecc0::   │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ or        ┆           │
│ 2      ┆ 1.7507e9   ┆ dns        ┆ mc.yandex ┆ … ┆ null      ┆ null      ┆ null      ┆ fdd8:7b12 │
│        ┆            ┆            ┆ .com.     ┆   ┆           ┆           ┆           ┆ :ecc0::   │
│ 3      ┆ 1.7507e9   ┆ data       ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ fdd8:7b12 │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ :ecc0::   │
│ 4      ┆ 1.7507e9   ┆ dns        ┆ mc.yandex ┆ … ┆ null      ┆ null      ┆ null      ┆ fdd8:7b12 │
│        ┆            ┆            ┆ .com.     ┆   ┆           ┆           ┆           ┆ :ecc0::   │
│ …      ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 419107 ┆ 1.7507e9   ┆ data       ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ fdd8:7b12 │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ :ecc0::   │
│ 419108 ┆ 1.7507e9   ┆ dns        ┆ gum.crite ┆ … ┆ null      ┆ null      ┆ null      ┆ fdd8:7b12 │
│        ┆            ┆            ┆ o.com.    ┆   ┆           ┆           ┆           ┆ :ecc0::   │
│ 419109 ┆ 1.7507e9   ┆ data       ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ fdd8:7b12 │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ :ecc0::   │
│ 419110 ┆ 1.7507e9   ┆ dns        ┆ gum.crite ┆ … ┆ 318965.0  ┆ null      ┆ applicati ┆ fdd8:7b12 │
│        ┆            ┆            ┆ o.com.    ┆   ┆           ┆           ┆ on/dns+cb ┆ :ecc0::   │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ or        ┆           │
│ 419111 ┆ 1.7507e9   ┆ data       ┆ null      ┆ … ┆ 318965.0  ┆ null      ┆ applicati ┆ fdd8:7b12 │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ on/dns+cb ┆ :ecc0::   │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ or        ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### [https-p2_cbor_dns_cbor.wpan.http.csv](data/https-p2_cbor_dns_cbor.wpan.http.csv)

shape: (631_368, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ frame.num ┆ frame.tim ┆ frame.pro ┆ tls.recor ┆ … ┆ http2.str ┆ http2.req ┆ http2.bod ┆ http2.he │
│ ber       ┆ e_epoch   ┆ tocols    ┆ d.content ┆   ┆ eamid     ┆ uest_in   ┆ y.reassem ┆ aders.co │
│ ---       ┆ ---       ┆ ---       ┆ _type     ┆   ┆ ---       ┆ ---       ┆ bled.in   ┆ ntent_ty │
│ i64       ┆ f64       ┆ str       ┆ ---       ┆   ┆ str       ┆ i64       ┆ ---       ┆ pe       │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 1.7507e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 1.7507e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ 1.7507e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ 1.7507e9  ┆ eth:ether ┆ 22        ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp:tls  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ 1.7507e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp      ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 631364    ┆ 1.7507e9  ┆ eth:ether ┆ 23        ┆ … ┆ 241395    ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp:tls: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ htt…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 631365    ┆ 1.7507e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 631366    ┆ 1.7507e9  ┆ eth:ether ┆ 23        ┆ … ┆ 241395,24 ┆ 631362    ┆ null      ┆ applicat │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆ 1395      ┆           ┆           ┆ ion/cbor │
│           ┆           ┆ :tcp:tls: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ htt…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 631367    ┆ 1.7507e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 631368    ┆ 1.7507e9  ┆ eth:ether ┆ 21        ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp:tls  ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## ✅ oscore-p2_cbor_dns_message.training.csv.gz OK

## ❌ Error in https-p2_json_dns_cbor.training.csv.gz

Number of Non-App frames 214727

### Broken table

shape: (419_112, 5)
┌────────┬──────────────┬──────────────────┬─────────────┬─────────────────────────────────┐
│        ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload                     │
│ ---    ┆ ---          ┆ ---              ┆ ---         ┆ ---                             │
│ i64    ┆ i64          ┆ f64              ┆ str         ┆ str                             │
╞════════╪══════════════╪══════════════════╪═════════════╪═════════════════════════════════╡
│ 0      ┆ 12           ┆ 1.7507e9         ┆ dns         ┆ 6000000000a50640fdd87b12eccc00… │
│ 1      ┆ 12           ┆ 1.7507e9         ┆ data        ┆ 6000000000a50640fdd87b12eccc00… │
│ 2      ┆ 14           ┆ 1.7507e9         ┆ dns         ┆ 6000000000850640fdd87b12eccc00… │
│ 3      ┆ 14           ┆ 1.7507e9         ┆ data        ┆ 6000000000850640fdd87b12eccc00… │
│ 4      ┆ 15           ┆ 1.7507e9         ┆ dns         ┆ 6000000000650640fdd87b12eccc00… │
│ …      ┆ …            ┆ …                ┆ …           ┆ …                               │
│ 419107 ┆ 317951       ┆ 1.7507e9         ┆ data        ┆ 6000000000950640fdd87b12eccc00… │
│ 419108 ┆ 317952       ┆ 1.7507e9         ┆ dns         ┆ 6000000000650640fdd87b12eccc00… │
│ 419109 ┆ 317952       ┆ 1.7507e9         ┆ data        ┆ 6000000000650640fdd87b12eccc00… │
│ 419110 ┆ 317954       ┆ 1.7507e9         ┆ dns         ┆ 6000000000e50640fdd87b12eccc00… │
│ 419111 ┆ 317954       ┆ 1.7507e9         ┆ data        ┆ 6000000000e50640fdd87b12eccc00… │
└────────┴──────────────┴──────────────────┴─────────────┴─────────────────────────────────┘

### Duplicate frame numbers

shape: (0, 5)
┌─────┬──────────────┬──────────────────┬─────────────┬─────────────┐
│     ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload │
│ --- ┆ ---          ┆ ---              ┆ ---         ┆ ---         │
│ i64 ┆ i64          ┆ f64              ┆ str         ┆ str         │
╞═════╪══════════════╪══════════════════╪═════════════╪═════════════╡
└─────┴──────────────┴──────────────────┴─────────────┴─────────────┘

### Expected App frames [204385]

shape: (209_556, 1)
┌───────────┐
│ frame.exp │
│ ---       │
│ i64       │
╞═══════════╡
│ 12        │
│ 14        │
│ 15        │
│ 19        │
│ 20        │
│ …         │
│ 317948    │
│ 317950    │
│ 317951    │
│ 317952    │
│ 317954    │
└───────────┘

### Different frame numbers

shape: (0, 1)
┌──────┐
│ diff │
│ ---  │
│ null │
╞══════╡
└──────┘

### Non-App frames

shape: (0, 5)
┌─────┬──────────────┬──────────────────┬─────────────┬─────────────┐
│     ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload │
│ --- ┆ ---          ┆ ---              ┆ ---         ┆ ---         │
│ i64 ┆ i64          ┆ f64              ┆ str         ┆ str         │
╞═════╪══════════════╪══════════════════╪═════════════╪═════════════╡
└─────┴──────────────┴──────────────────┴─────────────┴─────────────┘

shape: (214_727, 1)
┌────────────────┐
│ non_app_frames │
│ ---            │
│ i64            │
╞════════════════╡
│ 1              │
│ 2              │
│ 3              │
│ 4              │
│ 5              │
│ …              │
│ 630380         │
│ 630382         │
│ 630386         │
│ 630388         │
│ 630392         │
└────────────────┘

### [https-p2_json_dns_cbor.merged.csv.gz](data/https-p2_json_dns_cbor.merged.csv.gz)

shape: (419_112, 29)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│        ┆ client.htt ┆ client.typ ┆ client.dn ┆ … ┆ http2.req ┆ http2.bod ┆ http2.hea ┆ upstream. │
│ ---    ┆ p.response ┆ e          ┆ s.qry.nam ┆   ┆ uest_in   ┆ y.reassem ┆ ders.cont ┆ ipv6.pref │
│ i64    ┆ .recv_time ┆ ---        ┆ e         ┆   ┆ ---       ┆ bled.in   ┆ ent_type  ┆ ix        │
│        ┆ …          ┆ str        ┆ ---       ┆   ┆ f64       ┆ ---       ┆ ---       ┆ ---       │
│        ┆ ---        ┆            ┆ str       ┆   ┆           ┆ str       ┆ str       ┆ str       │
│        ┆ f64        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0      ┆ 1.7507e9   ┆ dns        ┆ mc.yandex ┆ … ┆ null      ┆ null      ┆ applicati ┆ fdd8:7b12 │
│        ┆            ┆            ┆ .com.     ┆   ┆           ┆           ┆ on/dns+cb ┆ :ecc0::   │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ or        ┆           │
│ 1      ┆ 1.7507e9   ┆ data       ┆ null      ┆ … ┆ null      ┆ null      ┆ applicati ┆ fdd8:7b12 │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ on/dns+cb ┆ :ecc0::   │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ or        ┆           │
│ 2      ┆ 1.7507e9   ┆ dns        ┆ mc.yandex ┆ … ┆ null      ┆ null      ┆ null      ┆ fdd8:7b12 │
│        ┆            ┆            ┆ .com.     ┆   ┆           ┆           ┆           ┆ :ecc0::   │
│ 3      ┆ 1.7507e9   ┆ data       ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ fdd8:7b12 │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ :ecc0::   │
│ 4      ┆ 1.7507e9   ┆ dns        ┆ mc.yandex ┆ … ┆ null      ┆ null      ┆ null      ┆ fdd8:7b12 │
│        ┆            ┆            ┆ .com.     ┆   ┆           ┆           ┆           ┆ :ecc0::   │
│ …      ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 419107 ┆ 1.7507e9   ┆ data       ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ fdd8:7b12 │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ :ecc0::   │
│ 419108 ┆ 1.7507e9   ┆ dns        ┆ gum.crite ┆ … ┆ null      ┆ null      ┆ null      ┆ fdd8:7b12 │
│        ┆            ┆            ┆ o.com.    ┆   ┆           ┆           ┆           ┆ :ecc0::   │
│ 419109 ┆ 1.7507e9   ┆ data       ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ fdd8:7b12 │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ :ecc0::   │
│ 419110 ┆ 1.7507e9   ┆ dns        ┆ gum.crite ┆ … ┆ 317950.0  ┆ null      ┆ applicati ┆ fdd8:7b12 │
│        ┆            ┆            ┆ o.com.    ┆   ┆           ┆           ┆ on/dns+cb ┆ :ecc0::   │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ or        ┆           │
│ 419111 ┆ 1.7507e9   ┆ data       ┆ null      ┆ … ┆ 317950.0  ┆ null      ┆ applicati ┆ fdd8:7b12 │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ on/dns+cb ┆ :ecc0::   │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ or        ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### [https-p2_json_dns_cbor.wpan.http.csv](data/https-p2_json_dns_cbor.wpan.http.csv)

shape: (630_393, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ frame.num ┆ frame.tim ┆ frame.pro ┆ tls.recor ┆ … ┆ http2.str ┆ http2.req ┆ http2.bod ┆ http2.he │
│ ber       ┆ e_epoch   ┆ tocols    ┆ d.content ┆   ┆ eamid     ┆ uest_in   ┆ y.reassem ┆ aders.co │
│ ---       ┆ ---       ┆ ---       ┆ _type     ┆   ┆ ---       ┆ ---       ┆ bled.in   ┆ ntent_ty │
│ i64       ┆ f64       ┆ str       ┆ ---       ┆   ┆ str       ┆ i64       ┆ ---       ┆ pe       │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 1.7507e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 1.7507e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ 1.7507e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ 1.7507e9  ┆ eth:ether ┆ 22        ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp:tls  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ 1.7507e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp      ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 630389    ┆ 1.7507e9  ┆ eth:ether ┆ 23        ┆ … ┆ 241395,24 ┆ null      ┆ null      ┆ applicat │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆ 1395      ┆           ┆           ┆ ion/json │
│           ┆           ┆ :tcp:tls: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ htt…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 630390    ┆ 1.7507e9  ┆ eth:ether ┆ 23        ┆ … ┆ 241395    ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp:tls: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ htt…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 630391    ┆ 1.7507e9  ┆ eth:ether ┆ 23        ┆ … ┆ 241395    ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp:tls: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ htt…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 630392    ┆ 1.7507e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 630393    ┆ 1.7507e9  ┆ eth:ether ┆ 23        ┆ … ┆ 241395,24 ┆ 630389    ┆ null      ┆ applicat │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆ 1395      ┆           ┆           ┆ ion/json │
│           ┆           ┆ :tcp:tls: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ htt…      ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## ✅ coap-d2_cbor_dns_message.training.csv.gz OK

## ✅ coap-d2_json_dns_cbor.training.csv.gz OK

## ✅ coap-p1_json_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-p2_json_dns_message.training.csv.gz OK

## ✅ oscore-base-d1_json_dns_message_b64.training.csv.gz OK

## ✅ coap-p1_cbor_dns_cbor.training.csv.gz OK

## ✅ oscore-base-d2_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ coap-p1_cbor_dns_message.training.csv.gz OK

## ✅ coaps-schc-d1_json_dns_message_b64.training.csv.gz OK

## ✅ oscore-d1_json_dns_cbor.training.csv.gz OK

## ✅ coap-p1_json_dns_cbor.training.csv.gz OK

## ✅ coap-p1_json_dns_message_b64.training.csv.gz OK

## ✅ coap-p2_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ coap-p2_cbor_dns_cbor.training.csv.gz OK

## ✅ oscore-base-d2_cbor_dns_message_b64.training.csv.gz OK

## ✅ coap-p2_cbor_dns_message.training.csv.gz OK

## ✅ coap-p2_json_dns_cbor.training.csv.gz OK

## ✅ oscore-d2_json_dns_cbor.training.csv.gz OK

## ✅ oscore-d1_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ coap-p2_cbor_dns_message_b64.training.csv.gz OK

## ✅ coaps-schc-d2-min-rules_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-p2_json_dns_cbor.training.csv.gz OK

## ✅ oscore-p1_json_dns_cbor.training.csv.gz OK

## ✅ oscore-d1_cbor_dns_message_b64.training.csv.gz OK

## ✅ coap-p2_json_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-base-p1_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ coap-d1_json_dns_message.training.csv.gz OK

## ✅ coap-d2_json_dns_message.training.csv.gz OK

## ✅ oscore-d2_json_dns_cbor_b64.training.csv.gz OK

## ✅ coap-p1_json_dns_message.training.csv.gz OK

## ✅ oscore-d1_json_dns_cbor_b64.training.csv.gz OK

## ✅ coap-p2_json_dns_message_b64.training.csv.gz OK

## ✅ coap-p2_json_dns_message.training.csv.gz OK

## ✅ oscore-base-p1_cbor_dns_message_b64.training.csv.gz OK

## ✅ https-d1_cbor_dns_cbor.training.csv.gz OK

## ✅ oscore-base-d1_cbor_dns_message.training.csv.gz OK

## ✅ oscore-d1_json_dns_message_b64.training.csv.gz OK

## ✅ oscore-base-d1_cbor_dns_cbor.training.csv.gz OK

## ✅ https-d1_cbor_dns_message.training.csv.gz OK

## ✅ oscore-base-d2_cbor_dns_cbor.training.csv.gz OK

## ✅ https-d1_json_dns_cbor.training.csv.gz OK

## ✅ oscore-base-p1_json_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-base-d1_json_dns_cbor.training.csv.gz OK

## ✅ https-d1_json_dns_message.training.csv.gz OK

## ✅ oscore-base-d1_json_dns_message.training.csv.gz OK

## ✅ oscore-d2_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-base-d2_cbor_dns_message.training.csv.gz OK

## ✅ https-d2_cbor_dns_cbor.training.csv.gz OK

## ✅ oscore-base-d2_json_dns_cbor.training.csv.gz OK

## ✅ https-d2_cbor_dns_message.training.csv.gz OK

## ✅ https-d2_json_dns_cbor.training.csv.gz OK

## ✅ oscore-base-d2_json_dns_message.training.csv.gz OK

## ✅ oscore-d2_cbor_dns_message_b64.training.csv.gz OK

## ✅ oscore-base-p1_json_dns_message_b64.training.csv.gz OK

## ✅ coaps-schc-d2-min-rules_cbor_dns_message_b64.training.csv.gz OK

## ✅ oscore-base-p1_cbor_dns_message.training.csv.gz OK

## ✅ https-d2_json_dns_message.training.csv.gz OK

## ✅ oscore-base-p1_cbor_dns_cbor.training.csv.gz OK

## ✅ oscore-base-p1_json_dns_cbor.training.csv.gz OK

## ✅ oscore-base-p1_json_dns_message.training.csv.gz OK

## ✅ oscore-base-p2_cbor_dns_cbor.training.csv.gz OK

## ✅ https-p1_cbor_dns_message.training.csv.gz OK

## ✅ oscore-base-p2_cbor_dns_message.training.csv.gz OK

## ✅ oscore-base-p2_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-base-p2_json_dns_cbor.training.csv.gz OK

## ✅ oscore-schc-d1_cbor_dns_cbor.training.csv.gz OK

## ✅ coaps-schc-d2-min-rules_json_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-base-p2_json_dns_message.training.csv.gz OK

## ✅ oscore-d2_json_dns_message_b64.training.csv.gz OK

## ✅ https-p1_json_dns_message.training.csv.gz OK

## ✅ coaps-schc-d2-peer-based_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ coaps-schc-d2-min-rules_json_dns_message_b64.training.csv.gz OK

## ❌ Error in https-p2_cbor_dns_message.training.csv.gz

Number of Non-App frames 218914

### Broken table

shape: (419_112, 5)
┌────────┬──────────────┬──────────────────┬─────────────┬─────────────────────────────────┐
│        ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload                     │
│ ---    ┆ ---          ┆ ---              ┆ ---         ┆ ---                             │
│ i64    ┆ i64          ┆ f64              ┆ str         ┆ str                             │
╞════════╪══════════════╪══════════════════╪═════════════╪═════════════════════════════════╡
│ 0      ┆ 12           ┆ 1.7507e9         ┆ dns         ┆ 6000000000a50640fdd87b12eccc00… │
│ 1      ┆ 12           ┆ 1.7507e9         ┆ data        ┆ 6000000000a50640fdd87b12eccc00… │
│ 2      ┆ 14           ┆ 1.7507e9         ┆ dns         ┆ 6000000000950640fdd87b12eccc00… │
│ 3      ┆ 14           ┆ 1.7507e9         ┆ data        ┆ 6000000000950640fdd87b12eccc00… │
│ 4      ┆ 15           ┆ 1.7507e9         ┆ dns         ┆ 6000000000650640fdd87b12eccc00… │
│ …      ┆ …            ┆ …                ┆ …           ┆ …                               │
│ 419107 ┆ 320558       ┆ 1.7507e9         ┆ data        ┆ 6000000000a50640fdd87b12eccc00… │
│ 419108 ┆ 320559       ┆ 1.7507e9         ┆ dns         ┆ 6000000000650640fdd87b12eccc00… │
│ 419109 ┆ 320559       ┆ 1.7507e9         ┆ data        ┆ 6000000000650640fdd87b12eccc00… │
│ 419110 ┆ 320561       ┆ 1.7507e9         ┆ dns         ┆ 6000000001250640fdd87b12eccc00… │
│ 419111 ┆ 320561       ┆ 1.7507e9         ┆ data        ┆ 6000000001250640fdd87b12eccc00… │
└────────┴──────────────┴──────────────────┴─────────────┴─────────────────────────────────┘

### Duplicate frame numbers

shape: (0, 5)
┌─────┬──────────────┬──────────────────┬─────────────┬─────────────┐
│     ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload │
│ --- ┆ ---          ┆ ---              ┆ ---         ┆ ---         │
│ i64 ┆ i64          ┆ f64              ┆ str         ┆ str         │
╞═════╪══════════════╪══════════════════╪═════════════╪═════════════╡
└─────┴──────────────┴──────────────────┴─────────────┴─────────────┘

### Expected App frames [200198]

shape: (209_556, 1)
┌───────────┐
│ frame.exp │
│ ---       │
│ i64       │
╞═══════════╡
│ 12        │
│ 14        │
│ 15        │
│ 19        │
│ 20        │
│ …         │
│ 320555    │
│ 320557    │
│ 320558    │
│ 320559    │
│ 320561    │
└───────────┘

### Different frame numbers

shape: (0, 1)
┌──────┐
│ diff │
│ ---  │
│ null │
╞══════╡
└──────┘

### Non-App frames

shape: (0, 5)
┌─────┬──────────────┬──────────────────┬─────────────┬─────────────┐
│     ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload │
│ --- ┆ ---          ┆ ---              ┆ ---         ┆ ---         │
│ i64 ┆ i64          ┆ f64              ┆ str         ┆ str         │
╞═════╪══════════════╪══════════════════╪═════════════╪═════════════╡
└─────┴──────────────┴──────────────────┴─────────────┴─────────────┘

shape: (218_914, 1)
┌────────────────┐
│ non_app_frames │
│ ---            │
│ i64            │
╞════════════════╡
│ 1              │
│ 2              │
│ 3              │
│ 4              │
│ 5              │
│ …              │
│ 634567         │
│ 634569         │
│ 634573         │
│ 634575         │
│ 634579         │
└────────────────┘

### [https-p2_cbor_dns_message.merged.csv.gz](data/https-p2_cbor_dns_message.merged.csv.gz)

shape: (419_112, 29)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│        ┆ client.htt ┆ client.typ ┆ client.dn ┆ … ┆ http2.req ┆ http2.bod ┆ http2.hea ┆ upstream. │
│ ---    ┆ p.response ┆ e          ┆ s.qry.nam ┆   ┆ uest_in   ┆ y.reassem ┆ ders.cont ┆ ipv6.pref │
│ i64    ┆ .recv_time ┆ ---        ┆ e         ┆   ┆ ---       ┆ bled.in   ┆ ent_type  ┆ ix        │
│        ┆ …          ┆ str        ┆ ---       ┆   ┆ f64       ┆ ---       ┆ ---       ┆ ---       │
│        ┆ ---        ┆            ┆ str       ┆   ┆           ┆ str       ┆ str       ┆ str       │
│        ┆ f64        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0      ┆ 1.7507e9   ┆ dns        ┆ mc.yandex ┆ … ┆ null      ┆ null      ┆ applicati ┆ fdd8:7b12 │
│        ┆            ┆            ┆ .com.     ┆   ┆           ┆           ┆ on/dns-me ┆ :ecc0::   │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ ssage     ┆           │
│ 1      ┆ 1.7507e9   ┆ data       ┆ null      ┆ … ┆ null      ┆ null      ┆ applicati ┆ fdd8:7b12 │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ on/dns-me ┆ :ecc0::   │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ ssage     ┆           │
│ 2      ┆ 1.7507e9   ┆ dns        ┆ mc.yandex ┆ … ┆ null      ┆ null      ┆ null      ┆ fdd8:7b12 │
│        ┆            ┆            ┆ .com.     ┆   ┆           ┆           ┆           ┆ :ecc0::   │
│ 3      ┆ 1.7507e9   ┆ data       ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ fdd8:7b12 │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ :ecc0::   │
│ 4      ┆ 1.7507e9   ┆ dns        ┆ mc.yandex ┆ … ┆ null      ┆ null      ┆ null      ┆ fdd8:7b12 │
│        ┆            ┆            ┆ .com.     ┆   ┆           ┆           ┆           ┆ :ecc0::   │
│ …      ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 419107 ┆ 1.7507e9   ┆ data       ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ fdd8:7b12 │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ :ecc0::   │
│ 419108 ┆ 1.7507e9   ┆ dns        ┆ gum.crite ┆ … ┆ null      ┆ null      ┆ null      ┆ fdd8:7b12 │
│        ┆            ┆            ┆ o.com.    ┆   ┆           ┆           ┆           ┆ :ecc0::   │
│ 419109 ┆ 1.7507e9   ┆ data       ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ fdd8:7b12 │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ :ecc0::   │
│ 419110 ┆ 1.7507e9   ┆ dns        ┆ gum.crite ┆ … ┆ 320557.0  ┆ null      ┆ applicati ┆ fdd8:7b12 │
│        ┆            ┆            ┆ o.com.    ┆   ┆           ┆           ┆ on/dns-me ┆ :ecc0::   │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ ssage     ┆           │
│ 419111 ┆ 1.7507e9   ┆ data       ┆ null      ┆ … ┆ 320557.0  ┆ null      ┆ applicati ┆ fdd8:7b12 │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ on/dns-me ┆ :ecc0::   │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ ssage     ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### [https-p2_cbor_dns_message.wpan.http.csv](data/https-p2_cbor_dns_message.wpan.http.csv)

shape: (634_580, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ frame.num ┆ frame.tim ┆ frame.pro ┆ tls.recor ┆ … ┆ http2.str ┆ http2.req ┆ http2.bod ┆ http2.he │
│ ber       ┆ e_epoch   ┆ tocols    ┆ d.content ┆   ┆ eamid     ┆ uest_in   ┆ y.reassem ┆ aders.co │
│ ---       ┆ ---       ┆ ---       ┆ _type     ┆   ┆ ---       ┆ ---       ┆ bled.in   ┆ ntent_ty │
│ i64       ┆ f64       ┆ str       ┆ ---       ┆   ┆ str       ┆ i64       ┆ ---       ┆ pe       │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 1.7507e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 1.7507e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ 1.7507e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ 1.7507e9  ┆ eth:ether ┆ 22        ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp:tls  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ 1.7507e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp      ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 634576    ┆ 1.7507e9  ┆ eth:ether ┆ 23        ┆ … ┆ 241395,24 ┆ null      ┆ null      ┆ applicat │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆ 1395      ┆           ┆           ┆ ion/cbor │
│           ┆           ┆ :tcp:tls: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ htt…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 634577    ┆ 1.7507e9  ┆ eth:ether ┆ 23        ┆ … ┆ 241395    ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp:tls: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ htt…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 634578    ┆ 1.7507e9  ┆ eth:ether ┆ 23        ┆ … ┆ 241395    ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp:tls: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ htt…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 634579    ┆ 1.7507e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 634580    ┆ 1.7507e9  ┆ eth:ether ┆ 23        ┆ … ┆ 241395,24 ┆ 634576    ┆ null      ┆ applicat │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆ 1395      ┆           ┆           ┆ ion/cbor │
│           ┆           ┆ :tcp:tls: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ htt…      ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## ✅ coaps-schc-d2-peer-based_cbor_dns_message_b64.training.csv.gz OK

## ✅ oscore-schc-d1_cbor_dns_message_b64.training.csv.gz OK

## ✅ oscore-base-p2_json_dns_message_b64.training.csv.gz OK

## ✅ coaps-schc-d2-peer-based_json_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-base-p2_cbor_dns_message_b64.training.csv.gz OK

## ✅ oscore-base-p2_json_dns_cbor_b64.training.csv.gz OK

## ❌ Error in https-p2_json_dns_message.training.csv.gz

Number of Non-App frames 218060

### Broken table

shape: (419_112, 5)
┌────────┬──────────────┬──────────────────┬─────────────┬─────────────────────────────────┐
│        ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload                     │
│ ---    ┆ ---          ┆ ---              ┆ ---         ┆ ---                             │
│ i64    ┆ i64          ┆ f64              ┆ str         ┆ str                             │
╞════════╪══════════════╪══════════════════╪═════════════╪═════════════════════════════════╡
│ 0      ┆ 12           ┆ 1.7507e9         ┆ dns         ┆ 6000000000a50640fdd87b12eccc00… │
│ 1      ┆ 12           ┆ 1.7507e9         ┆ data        ┆ 6000000000a50640fdd87b12eccc00… │
│ 2      ┆ 14           ┆ 1.7507e9         ┆ dns         ┆ 6000000000950640fdd87b12eccc00… │
│ 3      ┆ 14           ┆ 1.7507e9         ┆ data        ┆ 6000000000950640fdd87b12eccc00… │
│ 4      ┆ 15           ┆ 1.7507e9         ┆ dns         ┆ 6000000000650640fdd87b12eccc00… │
│ …      ┆ …            ┆ …                ┆ …           ┆ …                               │
│ 419107 ┆ 321040       ┆ 1.7507e9         ┆ data        ┆ 6000000000a50640fdd87b12eccc00… │
│ 419108 ┆ 321041       ┆ 1.7507e9         ┆ dns         ┆ 6000000000650640fdd87b12eccc00… │
│ 419109 ┆ 321041       ┆ 1.7507e9         ┆ data        ┆ 6000000000650640fdd87b12eccc00… │
│ 419110 ┆ 321043       ┆ 1.7507e9         ┆ dns         ┆ 6000000001250640fdd87b12eccc00… │
│ 419111 ┆ 321043       ┆ 1.7507e9         ┆ data        ┆ 6000000001250640fdd87b12eccc00… │
└────────┴──────────────┴──────────────────┴─────────────┴─────────────────────────────────┘

### Duplicate frame numbers

shape: (0, 5)
┌─────┬──────────────┬──────────────────┬─────────────┬─────────────┐
│     ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload │
│ --- ┆ ---          ┆ ---              ┆ ---         ┆ ---         │
│ i64 ┆ i64          ┆ f64              ┆ str         ┆ str         │
╞═════╪══════════════╪══════════════════╪═════════════╪═════════════╡
└─────┴──────────────┴──────────────────┴─────────────┴─────────────┘

### Expected App frames [201052]

shape: (209_556, 1)
┌───────────┐
│ frame.exp │
│ ---       │
│ i64       │
╞═══════════╡
│ 12        │
│ 14        │
│ 15        │
│ 19        │
│ 21        │
│ …         │
│ 321037    │
│ 321039    │
│ 321040    │
│ 321041    │
│ 321043    │
└───────────┘

### Different frame numbers

shape: (0, 1)
┌──────┐
│ diff │
│ ---  │
│ null │
╞══════╡
└──────┘

### Non-App frames

shape: (0, 5)
┌─────┬──────────────┬──────────────────┬─────────────┬─────────────┐
│     ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload │
│ --- ┆ ---          ┆ ---              ┆ ---         ┆ ---         │
│ i64 ┆ i64          ┆ f64              ┆ str         ┆ str         │
╞═════╪══════════════╪══════════════════╪═════════════╪═════════════╡
└─────┴──────────────┴──────────────────┴─────────────┴─────────────┘

shape: (218_060, 1)
┌────────────────┐
│ non_app_frames │
│ ---            │
│ i64            │
╞════════════════╡
│ 1              │
│ 2              │
│ 3              │
│ 4              │
│ 5              │
│ …              │
│ 633717         │
│ 633719         │
│ 633723         │
│ 633725         │
│ 633726         │
└────────────────┘

### [https-p2_json_dns_message.merged.csv.gz](data/https-p2_json_dns_message.merged.csv.gz)

shape: (419_112, 29)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│        ┆ client.htt ┆ client.typ ┆ client.dn ┆ … ┆ http2.req ┆ http2.bod ┆ http2.hea ┆ upstream. │
│ ---    ┆ p.response ┆ e          ┆ s.qry.nam ┆   ┆ uest_in   ┆ y.reassem ┆ ders.cont ┆ ipv6.pref │
│ i64    ┆ .recv_time ┆ ---        ┆ e         ┆   ┆ ---       ┆ bled.in   ┆ ent_type  ┆ ix        │
│        ┆ …          ┆ str        ┆ ---       ┆   ┆ f64       ┆ ---       ┆ ---       ┆ ---       │
│        ┆ ---        ┆            ┆ str       ┆   ┆           ┆ str       ┆ str       ┆ str       │
│        ┆ f64        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0      ┆ 1.7507e9   ┆ dns        ┆ mc.yandex ┆ … ┆ null      ┆ null      ┆ applicati ┆ fdd8:7b12 │
│        ┆            ┆            ┆ .com.     ┆   ┆           ┆           ┆ on/dns-me ┆ :ecc0::   │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ ssage     ┆           │
│ 1      ┆ 1.7507e9   ┆ data       ┆ null      ┆ … ┆ null      ┆ null      ┆ applicati ┆ fdd8:7b12 │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ on/dns-me ┆ :ecc0::   │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ ssage     ┆           │
│ 2      ┆ 1.7507e9   ┆ dns        ┆ mc.yandex ┆ … ┆ null      ┆ null      ┆ null      ┆ fdd8:7b12 │
│        ┆            ┆            ┆ .com.     ┆   ┆           ┆           ┆           ┆ :ecc0::   │
│ 3      ┆ 1.7507e9   ┆ data       ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ fdd8:7b12 │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ :ecc0::   │
│ 4      ┆ 1.7507e9   ┆ dns        ┆ mc.yandex ┆ … ┆ null      ┆ null      ┆ null      ┆ fdd8:7b12 │
│        ┆            ┆            ┆ .com.     ┆   ┆           ┆           ┆           ┆ :ecc0::   │
│ …      ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 419107 ┆ 1.7507e9   ┆ data       ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ fdd8:7b12 │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ :ecc0::   │
│ 419108 ┆ 1.7507e9   ┆ dns        ┆ gum.crite ┆ … ┆ null      ┆ null      ┆ null      ┆ fdd8:7b12 │
│        ┆            ┆            ┆ o.com.    ┆   ┆           ┆           ┆           ┆ :ecc0::   │
│ 419109 ┆ 1.7507e9   ┆ data       ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ fdd8:7b12 │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ :ecc0::   │
│ 419110 ┆ 1.7507e9   ┆ dns        ┆ gum.crite ┆ … ┆ 321039.0  ┆ null      ┆ applicati ┆ fdd8:7b12 │
│        ┆            ┆            ┆ o.com.    ┆   ┆           ┆           ┆ on/dns-me ┆ :ecc0::   │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ ssage     ┆           │
│ 419111 ┆ 1.7507e9   ┆ data       ┆ null      ┆ … ┆ 321039.0  ┆ null      ┆ applicati ┆ fdd8:7b12 │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ on/dns-me ┆ :ecc0::   │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ ssage     ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### [https-p2_json_dns_message.wpan.http.csv](data/https-p2_json_dns_message.wpan.http.csv)

shape: (633_726, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ frame.num ┆ frame.tim ┆ frame.pro ┆ tls.recor ┆ … ┆ http2.str ┆ http2.req ┆ http2.bod ┆ http2.he │
│ ber       ┆ e_epoch   ┆ tocols    ┆ d.content ┆   ┆ eamid     ┆ uest_in   ┆ y.reassem ┆ aders.co │
│ ---       ┆ ---       ┆ ---       ┆ _type     ┆   ┆ ---       ┆ ---       ┆ bled.in   ┆ ntent_ty │
│ i64       ┆ f64       ┆ str       ┆ ---       ┆   ┆ str       ┆ i64       ┆ ---       ┆ pe       │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 1.7507e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 1.7507e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ 1.7507e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ 1.7507e9  ┆ eth:ether ┆ 22        ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp:tls  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ 1.7507e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp      ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 633722    ┆ 1.7507e9  ┆ eth:ether ┆ 23        ┆ … ┆ 241395    ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp:tls: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ htt…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 633723    ┆ 1.7507e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 633724    ┆ 1.7507e9  ┆ eth:ether ┆ 23        ┆ … ┆ 241395,24 ┆ 633720    ┆ null      ┆ applicat │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆ 1395      ┆           ┆           ┆ ion/json │
│           ┆           ┆ :tcp:tls: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ htt…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 633725    ┆ 1.7507e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 633726    ┆ 1.7507e9  ┆ eth:ether ┆ 21        ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :tcp:tls  ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## ✅ oscore-p1_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ coaps-schc-d2-peer-based_json_dns_message_b64.training.csv.gz OK

## ✅ coaps-schc-d2_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-base-schc-d1_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-p1_cbor_dns_message_b64.training.csv.gz OK

## ✅ coaps-schc-d2_cbor_dns_message_b64.training.csv.gz OK

## ✅ oscore-base-schc-d1_cbor_dns_message_b64.training.csv.gz OK

## ❌ Error in oscore-p1_json_dns_cbor_b64.training.csv.gz

Number of Non-App frames 2246

### Broken table

shape: (877_639, 5)
┌────────┬──────────────┬──────────────────┬─────────────┬─────────────────────────────────┐
│        ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload                     │
│ ---    ┆ ---          ┆ ---              ┆ ---         ┆ ---                             │
│ i64    ┆ i64          ┆ f64              ┆ str         ┆ str                             │
╞════════╪══════════════╪══════════════════╪═════════════╪═════════════════════════════════╡
│ 0      ┆ 1            ┆ 1.7503e9         ┆ dns         ┆ 6000000000671140fdd86b0ceccc00… │
│ 1      ┆ 3            ┆ 1.7503e9         ┆ dns         ┆ 60000000005d1140fdd86b0ceccc00… │
│ 2      ┆ 5            ┆ 1.7503e9         ┆ data        ┆ 6000000000981140fdd86b0ceccc00… │
│ 3      ┆ 6            ┆ 1.7503e9         ┆ data        ┆ 6000000000281140fdd86b0ceccc00… │
│ 4      ┆ 7            ┆ 1.7503e9         ┆ data        ┆ 6000000000941140fdd86b0ceccc00… │
│ …      ┆ …            ┆ …                ┆ …           ┆ …                               │
│ 877634 ┆ 879883       ┆ 1.7504e9         ┆ data        ┆ 60000000006a1140fdd86b0ceccc00… │
│ 877635 ┆ 879884       ┆ 1.7504e9         ┆ data        ┆ 60000000004e1140fdd86b0ceccc00… │
│ 877636 ┆ 879885       ┆ 1.7504e9         ┆ data        ┆ 60000000006a1140fdd86b0ceccc00… │
│ 877637 ┆ 879886       ┆ 1.7504e9         ┆ data        ┆ 60000000004e1140fdd86b0ceccc00… │
│ 877638 ┆ 879887       ┆ 1.7504e9         ┆ data        ┆ 60000000006a1140fdd86b0ceccc00… │
└────────┴──────────────┴──────────────────┴─────────────┴─────────────────────────────────┘

### Duplicate frame numbers

shape: (0, 5)
┌─────┬──────────────┬──────────────────┬─────────────┬─────────────┐
│     ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload │
│ --- ┆ ---          ┆ ---              ┆ ---         ┆ ---         │
│ i64 ┆ i64          ┆ f64              ┆ str         ┆ str         │
╞═════╪══════════════╪══════════════════╪═════════════╪═════════════╡
└─────┴──────────────┴──────────────────┴─────────────┴─────────────┘

### Expected App frames [875393]

shape: (877_641, 1)
┌───────────┐
│ frame.exp │
│ ---       │
│ i64       │
╞═══════════╡
│ 1         │
│ 3         │
│ 5         │
│ 6         │
│ 7         │
│ …         │
│ 879883    │
│ 879884    │
│ 879885    │
│ 879886    │
│ 879887    │
└───────────┘

### Different frame numbers

shape: (2, 1)
┌───────┐
│ diff  │
│ ---   │
│ i64   │
╞═══════╡
│ 45133 │
│ 45134 │
└───────┘

### Non-App frames

shape: (0, 5)
┌─────┬──────────────┬──────────────────┬─────────────┬─────────────┐
│     ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload │
│ --- ┆ ---          ┆ ---              ┆ ---         ┆ ---         │
│ i64 ┆ i64          ┆ f64              ┆ str         ┆ str         │
╞═════╪══════════════╪══════════════════╪═════════════╪═════════════╡
└─────┴──────────────┴──────────────────┴─────────────┴─────────────┘

shape: (2_246, 1)
┌────────────────┐
│ non_app_frames │
│ ---            │
│ i64            │
╞════════════════╡
│ 2              │
│ 4              │
│ 248            │
│ 250            │
│ 268            │
│ …              │
│ 864025         │
│ 868203         │
│ 868205         │
│ 877667         │
│ 877669         │
└────────────────┘

### [oscore-p1_json_dns_cbor_b64.merged.csv.gz](data/oscore-p1_json_dns_cbor_b64.merged.csv.gz)

shape: (877_641, 54)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│        ┆ client.coa ┆ client.typ ┆ client.dn ┆ … ┆ upstream. ┆ upstream. ┆ upstream. ┆ upstream. │
│ ---    ┆ p.response ┆ e          ┆ s.qry.nam ┆   ┆ oscore.op ┆ oscore.op ┆ oscore.op ┆ oscore.op │
│ i64    ┆ .recv_time ┆ ---        ┆ e         ┆   ┆ t.ctype   ┆ t.block_n ┆ t.block_m ┆ t.block_s │
│        ┆ …          ┆ str        ┆ ---       ┆   ┆ ---       ┆ umb…      ┆ fla…      ┆ ize       │
│        ┆ ---        ┆            ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│        ┆ f64        ┆            ┆           ┆   ┆           ┆ str       ┆ str       ┆ str       │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0      ┆ 1.7503e9   ┆ dns        ┆ mc.yandex ┆ … ┆ Unknown   ┆ 0         ┆ 0         ┆ 2         │
│        ┆            ┆            ┆ .com.     ┆   ┆ Type 53   ┆           ┆           ┆           │
│ 1      ┆ 1.7503e9   ┆ dns        ┆ mc.yandex ┆ … ┆ Unknown   ┆ null      ┆ null      ┆ null      │
│        ┆            ┆            ┆ .com.     ┆   ┆ Type 53   ┆           ┆           ┆           │
│ 2      ┆ 1.7503e9   ┆ data       ┆ null      ┆ … ┆ applicati ┆ 0         ┆ 1         ┆ 2         │
│        ┆            ┆            ┆           ┆   ┆ on/json   ┆           ┆           ┆           │
│ 3      ┆ 1.7503e9   ┆ data       ┆ null      ┆ … ┆ null      ┆ 0         ┆ 1         ┆ 2         │
│ 4      ┆ 1.7503e9   ┆ data       ┆ null      ┆ … ┆ applicati ┆ 1         ┆ 1         ┆ 2         │
│        ┆            ┆            ┆           ┆   ┆ on/json   ┆           ┆           ┆           │
│ …      ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 877636 ┆ 1.7504e9   ┆ data       ┆ null      ┆ … ┆ applicati ┆ 1         ┆ 1         ┆ 2         │
│        ┆            ┆            ┆           ┆   ┆ on/json   ┆           ┆           ┆           │
│ 877637 ┆ 1.7504e9   ┆ data       ┆ null      ┆ … ┆ applicati ┆ 2         ┆ 0         ┆ 2         │
│        ┆            ┆            ┆           ┆   ┆ on/json   ┆           ┆           ┆           │
│ 877638 ┆ 1.7504e9   ┆ data       ┆ null      ┆ … ┆ applicati ┆ 2         ┆ 1         ┆ 2         │
│        ┆            ┆            ┆           ┆   ┆ on/json   ┆           ┆           ┆           │
│ 877639 ┆ 1.7504e9   ┆ data       ┆ null      ┆ … ┆ applicati ┆ 3         ┆ 0         ┆ 2         │
│        ┆            ┆            ┆           ┆   ┆ on/json   ┆           ┆           ┆           │
│ 877640 ┆ 1.7504e9   ┆ data       ┆ null      ┆ … ┆ applicati ┆ 3         ┆ 1         ┆ 2         │
│        ┆            ┆            ┆           ┆   ┆ on/json   ┆           ┆           ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### [oscore-p1_json_dns_cbor_b64.wpan.coap.csv](data/oscore-p1_json_dns_cbor_b64.wpan.coap.csv)

shape: (879_887, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ frame.num ┆ frame.tim ┆ frame.pro ┆ dtls.reco ┆ … ┆ oscore.op ┆ oscore.op ┆ oscore.op ┆ oscore.o │
│ ber       ┆ e_epoch   ┆ tocols    ┆ rd.conten ┆   ┆ t.ctype   ┆ t.block_n ┆ t.block_m ┆ pt.block │
│ ---       ┆ ---       ┆ ---       ┆ t_type    ┆   ┆ ---       ┆ umber     ┆ flag      ┆ _size    │
│ i64       ┆ f64       ┆ str       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 1.7503e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :udp:coap ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :da…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 1.7503e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :udp:coap ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ 1.7503e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :udp:coap ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :da…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ 1.7503e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :udp:coap ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ 1.7503e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :udp:coap ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :da…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 879883    ┆ 1.7504e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :udp:coap ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :da…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 879884    ┆ 1.7504e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :udp:coap ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :da…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 879885    ┆ 1.7504e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :udp:coap ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :da…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 879886    ┆ 1.7504e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :udp:coap ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :da…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 879887    ┆ 1.7504e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :udp:coap ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :da…      ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## ✅ coaps-schc-d2_json_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-base-schc-d1_json_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-p1_json_dns_message_b64.training.csv.gz OK

## ✅ coaps-schc-d2_json_dns_message_b64.training.csv.gz OK

## ✅ oscore-p2_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-base-schc-d1_cbor_dns_cbor.training.csv.gz OK

## ✅ coaps-schc-p1_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-p2_cbor_dns_message_b64.training.csv.gz OK

## ✅ oscore-base-schc-d1_json_dns_message_b64.training.csv.gz OK

## ✅ coaps-schc-p1_cbor_dns_message_b64.training.csv.gz OK

## ✅ coaps-schc-d1_cbor_dns_cbor.training.csv.gz OK

## ✅ oscore-schc-d1_cbor_dns_message.training.csv.gz OK

## ❌ Error in oscore-p2_json_dns_cbor_b64.training.csv.gz

Number of Non-App frames 2397

### Broken table

shape: (877_635, 5)
┌────────┬──────────────┬──────────────────┬─────────────┬─────────────────────────────────┐
│        ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload                     │
│ ---    ┆ ---          ┆ ---              ┆ ---         ┆ ---                             │
│ i64    ┆ i64          ┆ f64              ┆ str         ┆ str                             │
╞════════╪══════════════╪══════════════════╪═════════════╪═════════════════════════════════╡
│ 0      ┆ 1            ┆ 1.7503e9         ┆ dns         ┆ 6000000000661140fdd86b12eccc00… │
│ 1      ┆ 2            ┆ 1.7503e9         ┆ dns         ┆ 60000000005d1140fdd86b12eccc00… │
│ 2      ┆ 3            ┆ 1.7503e9         ┆ data        ┆ 6000000000981140fdd86b12eccc00… │
│ 3      ┆ 4            ┆ 1.7503e9         ┆ data        ┆ 6000000000281140fdd86b12eccc00… │
│ 4      ┆ 5            ┆ 1.7503e9         ┆ data        ┆ 6000000000941140fdd86b12eccc00… │
│ …      ┆ …            ┆ …                ┆ …           ┆ …                               │
│ 877630 ┆ 880030       ┆ 1.7504e9         ┆ data        ┆ 60000000006a1140fdd86b12eccc00… │
│ 877631 ┆ 880031       ┆ 1.7504e9         ┆ data        ┆ 60000000004e1140fdd86b12eccc00… │
│ 877632 ┆ 880032       ┆ 1.7504e9         ┆ data        ┆ 60000000006a1140fdd86b12eccc00… │
│ 877633 ┆ 880033       ┆ 1.7504e9         ┆ data        ┆ 60000000004e1140fdd86b12eccc00… │
│ 877634 ┆ 880034       ┆ 1.7504e9         ┆ data        ┆ 60000000006a1140fdd86b12eccc00… │
└────────┴──────────────┴──────────────────┴─────────────┴─────────────────────────────────┘

### Duplicate frame numbers

shape: (0, 5)
┌─────┬──────────────┬──────────────────┬─────────────┬─────────────┐
│     ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload │
│ --- ┆ ---          ┆ ---              ┆ ---         ┆ ---         │
│ i64 ┆ i64          ┆ f64              ┆ str         ┆ str         │
╞═════╪══════════════╪══════════════════╪═════════════╪═════════════╡
└─────┴──────────────┴──────────────────┴─────────────┴─────────────┘

### Expected App frames [875238]

shape: (877_637, 1)
┌───────────┐
│ frame.exp │
│ ---       │
│ i64       │
╞═══════════╡
│ 1         │
│ 2         │
│ 3         │
│ 4         │
│ 5         │
│ …         │
│ 880030    │
│ 880031    │
│ 880032    │
│ 880033    │
│ 880034    │
└───────────┘

### Different frame numbers

shape: (2, 1)
┌────────┐
│ diff   │
│ ---    │
│ i64    │
╞════════╡
│ 864619 │
│ 864620 │
└────────┘

### Non-App frames

shape: (0, 5)
┌─────┬──────────────┬──────────────────┬─────────────┬─────────────┐
│     ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload │
│ --- ┆ ---          ┆ ---              ┆ ---         ┆ ---         │
│ i64 ┆ i64          ┆ f64              ┆ str         ┆ str         │
╞═════╪══════════════╪══════════════════╪═════════════╪═════════════╡
└─────┴──────────────┴──────────────────┴─────────────┴─────────────┘

shape: (2_397, 1)
┌────────────────┐
│ non_app_frames │
│ ---            │
│ i64            │
╞════════════════╡
│ 36             │
│ 38             │
│ 250            │
│ 252            │
│ 266            │
│ …              │
│ 874140         │
│ 874520         │
│ 874522         │
│ 876026         │
│ 876028         │
└────────────────┘

### [oscore-p2_json_dns_cbor_b64.merged.csv.gz](data/oscore-p2_json_dns_cbor_b64.merged.csv.gz)

shape: (877_637, 54)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│        ┆ client.coa ┆ client.typ ┆ client.dn ┆ … ┆ upstream. ┆ upstream. ┆ upstream. ┆ upstream. │
│ ---    ┆ p.response ┆ e          ┆ s.qry.nam ┆   ┆ oscore.op ┆ oscore.op ┆ oscore.op ┆ oscore.op │
│ i64    ┆ .recv_time ┆ ---        ┆ e         ┆   ┆ t.ctype   ┆ t.block_n ┆ t.block_m ┆ t.block_s │
│        ┆ …          ┆ str        ┆ ---       ┆   ┆ ---       ┆ umb…      ┆ fla…      ┆ ize       │
│        ┆ ---        ┆            ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│        ┆ f64        ┆            ┆           ┆   ┆           ┆ str       ┆ str       ┆ str       │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0      ┆ 1.7503e9   ┆ dns        ┆ mc.yandex ┆ … ┆ Unknown   ┆ 0         ┆ 0         ┆ 2         │
│        ┆            ┆            ┆ .com.     ┆   ┆ Type 53   ┆           ┆           ┆           │
│ 1      ┆ 1.7503e9   ┆ dns        ┆ mc.yandex ┆ … ┆ Unknown   ┆ null      ┆ null      ┆ null      │
│        ┆            ┆            ┆ .com.     ┆   ┆ Type 53   ┆           ┆           ┆           │
│ 2      ┆ 1.7503e9   ┆ data       ┆ null      ┆ … ┆ applicati ┆ 0         ┆ 1         ┆ 2         │
│        ┆            ┆            ┆           ┆   ┆ on/json   ┆           ┆           ┆           │
│ 3      ┆ 1.7503e9   ┆ data       ┆ null      ┆ … ┆ null      ┆ 0         ┆ 1         ┆ 2         │
│ 4      ┆ 1.7503e9   ┆ data       ┆ null      ┆ … ┆ applicati ┆ 1         ┆ 1         ┆ 2         │
│        ┆            ┆            ┆           ┆   ┆ on/json   ┆           ┆           ┆           │
│ …      ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 877632 ┆ 1.7504e9   ┆ data       ┆ null      ┆ … ┆ applicati ┆ 1         ┆ 1         ┆ 2         │
│        ┆            ┆            ┆           ┆   ┆ on/json   ┆           ┆           ┆           │
│ 877633 ┆ 1.7504e9   ┆ data       ┆ null      ┆ … ┆ applicati ┆ 2         ┆ 0         ┆ 2         │
│        ┆            ┆            ┆           ┆   ┆ on/json   ┆           ┆           ┆           │
│ 877634 ┆ 1.7504e9   ┆ data       ┆ null      ┆ … ┆ applicati ┆ 2         ┆ 1         ┆ 2         │
│        ┆            ┆            ┆           ┆   ┆ on/json   ┆           ┆           ┆           │
│ 877635 ┆ 1.7504e9   ┆ data       ┆ null      ┆ … ┆ applicati ┆ 3         ┆ 0         ┆ 2         │
│        ┆            ┆            ┆           ┆   ┆ on/json   ┆           ┆           ┆           │
│ 877636 ┆ 1.7504e9   ┆ data       ┆ null      ┆ … ┆ applicati ┆ 3         ┆ 1         ┆ 2         │
│        ┆            ┆            ┆           ┆   ┆ on/json   ┆           ┆           ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### [oscore-p2_json_dns_cbor_b64.wpan.coap.csv](data/oscore-p2_json_dns_cbor_b64.wpan.coap.csv)

shape: (880_034, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ frame.num ┆ frame.tim ┆ frame.pro ┆ dtls.reco ┆ … ┆ oscore.op ┆ oscore.op ┆ oscore.op ┆ oscore.o │
│ ber       ┆ e_epoch   ┆ tocols    ┆ rd.conten ┆   ┆ t.ctype   ┆ t.block_n ┆ t.block_m ┆ pt.block │
│ ---       ┆ ---       ┆ ---       ┆ t_type    ┆   ┆ ---       ┆ umber     ┆ flag      ┆ _size    │
│ i64       ┆ f64       ┆ str       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 1.7503e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :udp:coap ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :da…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 1.7503e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :udp:coap ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :da…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ 1.7503e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :udp:coap ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :da…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ 1.7503e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :udp:coap ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :da…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ 1.7503e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :udp:coap ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :da…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 880030    ┆ 1.7504e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :udp:coap ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :da…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 880031    ┆ 1.7504e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :udp:coap ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :da…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 880032    ┆ 1.7504e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :udp:coap ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :da…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 880033    ┆ 1.7504e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :udp:coap ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :da…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 880034    ┆ 1.7504e9  ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ type:ipv6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :udp:coap ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ :da…      ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## ✅ oscore-base-schc-d1_cbor_dns_message.training.csv.gz OK

## ✅ oscore-p2_json_dns_message_b64.training.csv.gz OK

## ✅ oscore-base-schc-d2-min-rules_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-schc-d1_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ coaps-schc-p1_json_dns_cbor_b64.training.csv.gz OK

## ✅ coaps-schc-d1_cbor_dns_message.training.csv.gz OK

## ✅ oscore-schc-d1_json_dns_cbor.training.csv.gz OK

## ✅ oscore-base-schc-d2-min-rules_cbor_dns_message_b64.training.csv.gz OK

## ✅ oscore-base-schc-d2-min-rules_json_dns_cbor_b64.training.csv.gz OK

## ✅ coaps-schc-p1_json_dns_message_b64.training.csv.gz OK

## ✅ oscore-base-schc-d1_json_dns_cbor.training.csv.gz OK

## ✅ coaps-schc-d1_json_dns_cbor.training.csv.gz OK

## ✅ oscore-schc-d1_json_dns_message.training.csv.gz OK

## ✅ coaps-schc-p2_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-schc-d1_json_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-base-schc-d2-min-rules_json_dns_message_b64.training.csv.gz OK

## ✅ oscore-schc-d2-min-rules_cbor_dns_cbor.training.csv.gz OK

## ✅ oscore-base-schc-d1_json_dns_message.training.csv.gz OK

## ✅ oscore-base-schc-d2-peer-based_json_dns_cbor_b64.training.csv.gz OK

## ✅ coaps-schc-d1_json_dns_message.training.csv.gz OK

## ✅ oscore-base-schc-d2-peer-based_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-base-schc-d2-min-rules_cbor_dns_cbor.training.csv.gz OK

## ✅ coaps-schc-d2-min-rules_cbor_dns_cbor.training.csv.gz OK

## ✅ oscore-schc-d2-min-rules_cbor_dns_message.training.csv.gz OK

## ✅ oscore-base-schc-d2-peer-based_cbor_dns_message_b64.training.csv.gz OK

## ✅ coaps-schc-p2_cbor_dns_message_b64.training.csv.gz OK

## ✅ oscore-schc-d1_json_dns_message_b64.training.csv.gz OK

## ✅ oscore-base-schc-d2-min-rules_cbor_dns_message.training.csv.gz OK

## ✅ oscore-schc-d2-min-rules_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ coaps-schc-p2_json_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-schc-d2-min-rules_json_dns_cbor.training.csv.gz OK

## ✅ coaps-schc-d2-min-rules_cbor_dns_message.training.csv.gz OK

## ✅ oscore-base-schc-d2-min-rules_json_dns_cbor.training.csv.gz OK

## ✅ oscore-base-schc-d2_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-schc-d2-min-rules_cbor_dns_message_b64.training.csv.gz OK

## ✅ oscore-base-schc-d2-peer-based_json_dns_message_b64.training.csv.gz OK

## ✅ coaps-schc-p2_json_dns_message_b64.training.csv.gz OK

## ✅ oscore-schc-d2-min-rules_json_dns_message.training.csv.gz OK

## ✅ coaps-schc-d2-min-rules_json_dns_cbor.training.csv.gz OK

## ✅ oscore-schc-d2-peer-based_cbor_dns_message_b64.training.csv.gz OK

## ✅ oscore-schc-d2-min-rules_json_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-base-schc-d2_cbor_dns_message_b64.training.csv.gz OK

## ✅ oscore-base-schc-d2-min-rules_json_dns_message.training.csv.gz OK

## ✅ oscore-schc-d2-min-rules_json_dns_message_b64.training.csv.gz OK

## ✅ oscore-schc-d2-peer-based_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-schc-d2-peer-based_cbor_dns_cbor.training.csv.gz OK

## ✅ oscore-base-schc-d2_json_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-base-schc-p1_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-base-schc-p1_cbor_dns_message_b64.training.csv.gz OK

## ✅ oscore-base-schc-d2-peer-based_cbor_dns_cbor.training.csv.gz OK

## ✅ coaps-schc-d2-min-rules_json_dns_message.training.csv.gz OK

## ✅ oscore-base-schc-d2_json_dns_message_b64.training.csv.gz OK

## ✅ oscore-schc-d2-peer-based_json_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-schc-d2-peer-based_cbor_dns_message.training.csv.gz OK

## ✅ oscore-schc-d2_cbor_dns_cbor.training.csv.gz OK

## ✅ oscore-base-schc-p1_json_dns_cbor_b64.training.csv.gz OK

## ✅ coaps-schc-d2-peer-based_cbor_dns_cbor.training.csv.gz OK

## ✅ oscore-base-schc-d2-peer-based_cbor_dns_message.training.csv.gz OK

## ✅ oscore-schc-d2-peer-based_json_dns_cbor.training.csv.gz OK

## ✅ oscore-schc-d2-peer-based_json_dns_message_b64.training.csv.gz OK

## ✅ oscore-schc-d2_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-base-schc-p2-min-rules_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-base-schc-p1_json_dns_message_b64.training.csv.gz OK

## ✅ coaps-schc-d2-peer-based_cbor_dns_message.training.csv.gz OK

## ✅ oscore-base-schc-d2-peer-based_json_dns_cbor.training.csv.gz OK

## ✅ oscore-base-schc-p2-min-rules_cbor_dns_message_b64.training.csv.gz OK

## ✅ oscore-base-schc-p2-min-rules_json_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-schc-d2_cbor_dns_message_b64.training.csv.gz OK

## ✅ oscore-schc-d2_json_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-schc-d2-peer-based_json_dns_message.training.csv.gz OK

## ✅ coaps-schc-d2-peer-based_json_dns_cbor.training.csv.gz OK

## ✅ oscore-schc-d2_json_dns_message_b64.training.csv.gz OK

## ✅ oscore-base-schc-p2-min-rules_json_dns_message_b64.training.csv.gz OK

## ✅ oscore-base-schc-p2_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-base-schc-d2-peer-based_json_dns_message.training.csv.gz OK

## ✅ coaps-schc-d2-peer-based_json_dns_message.training.csv.gz OK

## ✅ oscore-base-schc-p2_cbor_dns_message_b64.training.csv.gz OK

## ✅ oscore-base-schc-d2_cbor_dns_cbor.training.csv.gz OK

## ❌ Error in oscore-schc-p1_cbor_dns_cbor_b64.training.csv.gz

Number of Non-App frames 586

### Broken table

shape: (922_106, 5)
┌────────┬──────────────┬──────────────────┬─────────────┬─────────────────────────────────┐
│        ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload                     │
│ ---    ┆ ---          ┆ ---              ┆ ---         ┆ ---                             │
│ i64    ┆ i64          ┆ f64              ┆ str         ┆ str                             │
╞════════╪══════════════╪══════════════════╪═════════════╪═════════════════════════════════╡
│ 0      ┆ 1            ┆ 1.7505e9         ┆ dns         ┆ 0147992064a5c40360df1195a9663f… │
│ 1      ┆ 2            ┆ 1.7505e9         ┆ dns         ┆ 01c7992064a5dae1c56bdfa3ac321e… │
│ 2      ┆ 3            ┆ 1.7505e9         ┆ data        ┆ 17002ad6b4825ee880fc6fd4689a16… │
│ 3      ┆ 4            ┆ 1.7505e9         ┆ data        ┆ 173572726e8c12522969c2e5d99afb… │
│ 4      ┆ 5            ┆ 1.7505e9         ┆ data        ┆ 01d6b5a412f7589ac49bae52030c85… │
│ …      ┆ …            ┆ …                ┆ …           ┆ …                               │
│ 922101 ┆ 922691       ┆ 1.7505e9         ┆ data        ┆ 01c1faaa249c614df70217f4212e89… │
│ 922102 ┆ 922692       ┆ 1.7505e9         ┆ data        ┆ 01460b89465fac18619c621170e8cd… │
│ 922103 ┆ 922693       ┆ 1.7505e9         ┆ data        ┆ 01c60b89465fa79888744f67b2e453… │
│ 922104 ┆ 922694       ┆ 1.7505e9         ┆ data        ┆ 015848e4983a0c1861a2a755e22580… │
│ 922105 ┆ 922695       ┆ 1.7505e9         ┆ data        ┆ 01d848e4983a136da638801990e79a… │
└────────┴──────────────┴──────────────────┴─────────────┴─────────────────────────────────┘

### Duplicate frame numbers

shape: (0, 5)
┌─────┬──────────────┬──────────────────┬─────────────┬─────────────┐
│     ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload │
│ --- ┆ ---          ┆ ---              ┆ ---         ┆ ---         │
│ i64 ┆ i64          ┆ f64              ┆ str         ┆ str         │
╞═════╪══════════════╪══════════════════╪═════════════╪═════════════╡
└─────┴──────────────┴──────────────────┴─────────────┴─────────────┘

### Expected App frames [921520]

shape: (922_109, 1)
┌───────────┐
│ frame.exp │
│ ---       │
│ i64       │
╞═══════════╡
│ 1         │
│ 2         │
│ 3         │
│ 4         │
│ 5         │
│ …         │
│ 922691    │
│ 922692    │
│ 922693    │
│ 922694    │
│ 922695    │
└───────────┘

### Different frame numbers

shape: (3, 1)
┌────────┐
│ diff   │
│ ---    │
│ i64    │
╞════════╡
│ 888468 │
│ 888469 │
│ 888470 │
└────────┘

### Non-App frames

shape: (0, 5)
┌─────┬──────────────┬──────────────────┬─────────────┬─────────────┐
│     ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload │
│ --- ┆ ---          ┆ ---              ┆ ---         ┆ ---         │
│ i64 ┆ i64          ┆ f64              ┆ str         ┆ str         │
╞═════╪══════════════╪══════════════════╪═════════════╪═════════════╡
└─────┴──────────────┴──────────────────┴─────────────┴─────────────┘

shape: (586, 1)
┌────────────────┐
│ non_app_frames │
│ ---            │
│ i64            │
╞════════════════╡
│ 4214           │
│ 4216           │
│ 5056           │
│ 5058           │
│ 5636           │
│ …              │
│ 874642         │
│ 883592         │
│ 883594         │
│ 920041         │
│ 920043         │
└────────────────┘

### [oscore-schc-p1_cbor_dns_cbor_b64.merged.csv.gz](data/oscore-schc-p1_cbor_dns_cbor_b64.merged.csv.gz)

shape: (922_108, 54)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│        ┆ client.coa ┆ client.typ ┆ client.dn ┆ … ┆ upstream. ┆ upstream. ┆ upstream. ┆ upstream. │
│ ---    ┆ p.response ┆ e          ┆ s.qry.nam ┆   ┆ oscore.op ┆ oscore.op ┆ oscore.op ┆ oscore.op │
│ i64    ┆ .recv_time ┆ ---        ┆ e         ┆   ┆ t.ctype   ┆ t.block_n ┆ t.block_m ┆ t.block_s │
│        ┆ …          ┆ str        ┆ ---       ┆   ┆ ---       ┆ umb…      ┆ fla…      ┆ ize       │
│        ┆ ---        ┆            ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│        ┆ f64        ┆            ┆           ┆   ┆           ┆ str       ┆ str       ┆ str       │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0      ┆ 1.7505e9   ┆ dns        ┆ mc.yandex ┆ … ┆ Unknown   ┆ 0         ┆ 0         ┆ 2         │
│        ┆            ┆            ┆ .com.     ┆   ┆ Type 53   ┆           ┆           ┆           │
│ 1      ┆ 1.7505e9   ┆ dns        ┆ mc.yandex ┆ … ┆ Unknown   ┆ null      ┆ null      ┆ null      │
│        ┆            ┆            ┆ .com.     ┆   ┆ Type 53   ┆           ┆           ┆           │
│ 2      ┆ 1.7505e9   ┆ data       ┆ null      ┆ … ┆ applicati ┆ 0         ┆ 1         ┆ 2         │
│        ┆            ┆            ┆           ┆   ┆ on/cbor   ┆           ┆           ┆           │
│ 3      ┆ 1.7505e9   ┆ data       ┆ null      ┆ … ┆ applicati ┆ 0         ┆ 1         ┆ 2         │
│        ┆            ┆            ┆           ┆   ┆ on/cbor   ┆           ┆           ┆           │
│ 4      ┆ 1.7505e9   ┆ data       ┆ null      ┆ … ┆ null      ┆ 0         ┆ 1         ┆ 2         │
│ …      ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 922103 ┆ 1.7505e9   ┆ data       ┆ null      ┆ … ┆ applicati ┆ 0,2       ┆ 1,0       ┆ 2,2       │
│        ┆            ┆            ┆           ┆   ┆ on/cbor   ┆           ┆           ┆           │
│ 922104 ┆ 1.7505e9   ┆ data       ┆ null      ┆ … ┆ applicati ┆ 1         ┆ 0         ┆ 2         │
│        ┆            ┆            ┆           ┆   ┆ on/cbor   ┆           ┆           ┆           │
│ 922105 ┆ 1.7505e9   ┆ data       ┆ null      ┆ … ┆ applicati ┆ 1         ┆ 1         ┆ 2         │
│        ┆            ┆            ┆           ┆   ┆ on/cbor   ┆           ┆           ┆           │
│ 922106 ┆ 1.7505e9   ┆ data       ┆ null      ┆ … ┆ applicati ┆ 2         ┆ 0         ┆ 2         │
│        ┆            ┆            ┆           ┆   ┆ on/cbor   ┆           ┆           ┆           │
│ 922107 ┆ 1.7505e9   ┆ data       ┆ null      ┆ … ┆ applicati ┆ 2         ┆ 1         ┆ 2         │
│        ┆            ┆            ┆           ┆   ┆ on/cbor   ┆           ┆           ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### [oscore-schc-p1_cbor_dns_cbor_b64.wpan.coap.csv](data/oscore-schc-p1_cbor_dns_cbor_b64.wpan.coap.csv)

shape: (922_695, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ frame.num ┆ frame.tim ┆ frame.pro ┆ dtls.reco ┆ … ┆ oscore.op ┆ oscore.op ┆ oscore.op ┆ oscore.o │
│ ber       ┆ e_epoch   ┆ tocols    ┆ rd.conten ┆   ┆ t.ctype   ┆ t.block_n ┆ t.block_m ┆ pt.block │
│ ---       ┆ ---       ┆ ---       ┆ t_type    ┆   ┆ ---       ┆ umber     ┆ flag      ┆ _size    │
│ i64       ┆ f64       ┆ str       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 1.7505e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 1.7505e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ 1.7505e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ 1.7505e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ 1.7505e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 922691    ┆ 1.7505e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 922692    ┆ 1.7505e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 922693    ┆ 1.7505e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 922694    ┆ 1.7505e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 922695    ┆ 1.7505e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## ✅ oscore-base-schc-p2_json_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-schc-d2_cbor_dns_message.training.csv.gz OK

## ✅ oscore-schc-p1_cbor_dns_message_b64.training.csv.gz OK

## ✅ oscore-base-schc-p2_json_dns_message_b64.training.csv.gz OK

## ✅ coaps-schc-d2_cbor_dns_cbor.training.csv.gz OK

## ✅ oscore-schc-p1_json_dns_message_b64.training.csv.gz OK

## ✅ oscore-base-schc-d2_cbor_dns_message.training.csv.gz OK

## ✅ oscore-schc-d2_json_dns_cbor.training.csv.gz OK

## ✅ coaps-schc-d2_cbor_dns_message.training.csv.gz OK

## ✅ oscore-schc-p1_json_dns_cbor_b64.training.csv.gz OK

## ✅ oscore-base-schc-d2_json_dns_cbor.training.csv.gz OK

## ✅ oscore-schc-p2_cbor_dns_cbor_b64.training.csv.gz OK

## ✅ coaps-schc-d2_json_dns_cbor.training.csv.gz OK

## ✅ oscore-schc-d2_json_dns_message.training.csv.gz OK

## ✅ oscore-base-schc-d2_json_dns_message.training.csv.gz OK

## ❌ Error in oscore-schc-p2_cbor_dns_message_b64.training.csv.gz

Number of Non-App frames 2950

### Broken table

shape: (1_045_887, 5)
┌─────────┬──────────────┬──────────────────┬─────────────┬─────────────────────────────────┐
│         ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload                     │
│ ---     ┆ ---          ┆ ---              ┆ ---         ┆ ---                             │
│ i64     ┆ i64          ┆ f64              ┆ str         ┆ str                             │
╞═════════╪══════════════╪══════════════════╪═════════════╪═════════════════════════════════╡
│ 0       ┆ 1            ┆ 1.7504e9         ┆ dns         ┆ 014d0d666ee3240360db0d91e01347… │
│ 1       ┆ 2            ┆ 1.7504e9         ┆ dns         ┆ 01cd0d666ee33ae1c57e62a54a4097… │
│ 2       ┆ 3            ┆ 1.7504e9         ┆ dns         ┆ 014d0344bf330407e37abf4099c6e8… │
│ 3       ┆ 4            ┆ 1.7504e9         ┆ dns         ┆ 01cd0344bf33189ac486e942f63ff4… │
│ 4       ┆ 5            ┆ 1.7504e9         ┆ data        ┆ 17002b8aec5c5f8c816f167da529db… │
│ …       ┆ …            ┆ …                ┆ …           ┆ …                               │
│ 1045882 ┆ 1048836      ┆ 1.7505e9         ┆ data        ┆ 0143ff4280e28c1c27ee992df8dbbd… │
│ 1045883 ┆ 1048837      ┆ 1.7505e9         ┆ data        ┆ 01c3ff4280e2921d10cef139541070… │
│ 1045884 ┆ 1048838      ┆ 1.7505e9         ┆ data        ┆ 014e77095aedec1c27f0af31060f2f… │
│ 1045885 ┆ 1048839      ┆ 1.7505e9         ┆ data        ┆ 01ce77095aeded4733c7677c58ed06… │
│ 1045886 ┆ 1048840      ┆ 1.7505e9         ┆ data        ┆ 01574d85ff882c1c27f6dc6062e914… │
└─────────┴──────────────┴──────────────────┴─────────────┴─────────────────────────────────┘

### Duplicate frame numbers

shape: (0, 5)
┌─────┬──────────────┬──────────────────┬─────────────┬─────────────┐
│     ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload │
│ --- ┆ ---          ┆ ---              ┆ ---         ┆ ---         │
│ i64 ┆ i64          ┆ f64              ┆ str         ┆ str         │
╞═════╪══════════════╪══════════════════╪═════════════╪═════════════╡
└─────┴──────────────┴──────────────────┴─────────────┴─────────────┘

### Expected App frames [1042937]

shape: (1_045_890, 1)
┌───────────┐
│ frame.exp │
│ ---       │
│ i64       │
╞═══════════╡
│ 1         │
│ 2         │
│ 3         │
│ 4         │
│ 5         │
│ …         │
│ 1048836   │
│ 1048837   │
│ 1048838   │
│ 1048839   │
│ 1048840   │
└───────────┘

### Different frame numbers

shape: (3, 1)
┌────────┐
│ diff   │
│ ---    │
│ i64    │
╞════════╡
│ 429348 │
│ 429349 │
│ 429350 │
└────────┘

### Non-App frames

shape: (0, 5)
┌─────┬──────────────┬──────────────────┬─────────────┬─────────────┐
│     ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload │
│ --- ┆ ---          ┆ ---              ┆ ---         ┆ ---         │
│ i64 ┆ i64          ┆ f64              ┆ str         ┆ str         │
╞═════╪══════════════╪══════════════════╪═════════════╪═════════════╡
└─────┴──────────────┴──────────────────┴─────────────┴─────────────┘

shape: (2_950, 1)
┌────────────────┐
│ non_app_frames │
│ ---            │
│ i64            │
╞════════════════╡
│ 852            │
│ 854            │
│ 951            │
│ 953            │
│ 1504           │
│ …              │
│ 1031278        │
│ 1031786        │
│ 1031788        │
│ 1034712        │
│ 1034714        │
└────────────────┘

### [oscore-schc-p2_cbor_dns_message_b64.merged.csv.gz](data/oscore-schc-p2_cbor_dns_message_b64.merged.csv.gz)

shape: (1_045_889, 54)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│         ┆ client.coa ┆ client.ty ┆ client.dn ┆ … ┆ upstream. ┆ upstream. ┆ upstream. ┆ upstream. │
│ ---     ┆ p.response ┆ pe        ┆ s.qry.nam ┆   ┆ oscore.op ┆ oscore.op ┆ oscore.op ┆ oscore.op │
│ i64     ┆ .recv_time ┆ ---       ┆ e         ┆   ┆ t.ctype   ┆ t.block_n ┆ t.block_m ┆ t.block_s │
│         ┆ …          ┆ str       ┆ ---       ┆   ┆ ---       ┆ umb…      ┆ fla…      ┆ ize       │
│         ┆ ---        ┆           ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│         ┆ f64        ┆           ┆           ┆   ┆           ┆ str       ┆ str       ┆ str       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0       ┆ 1.7504e9   ┆ dns       ┆ mc.yandex ┆ … ┆ Unknown   ┆ 0         ┆ 0         ┆ 2         │
│         ┆            ┆           ┆ .com.     ┆   ┆ Type 553  ┆           ┆           ┆           │
│ 1       ┆ 1.7504e9   ┆ dns       ┆ mc.yandex ┆ … ┆ Unknown   ┆ 0         ┆ 1         ┆ 2         │
│         ┆            ┆           ┆ .com.     ┆   ┆ Type 553  ┆           ┆           ┆           │
│ 2       ┆ 1.7504e9   ┆ dns       ┆ mc.yandex ┆ … ┆ Unknown   ┆ 1         ┆ 0         ┆ 2         │
│         ┆            ┆           ┆ .com.     ┆   ┆ Type 553  ┆           ┆           ┆           │
│ 3       ┆ 1.7504e9   ┆ dns       ┆ mc.yandex ┆ … ┆ Unknown   ┆ 1         ┆ 0         ┆ 2         │
│         ┆            ┆           ┆ .com.     ┆   ┆ Type 553  ┆           ┆           ┆           │
│ 4       ┆ 1.7504e9   ┆ data      ┆ null      ┆ … ┆ applicati ┆ 0         ┆ 1         ┆ 2         │
│         ┆            ┆           ┆           ┆   ┆ on/cbor   ┆           ┆           ┆           │
│ …       ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 1045884 ┆ 1.7505e9   ┆ data      ┆ null      ┆ … ┆ applicati ┆ 2         ┆ 0         ┆ 2         │
│         ┆            ┆           ┆           ┆   ┆ on/cbor   ┆           ┆           ┆           │
│ 1045885 ┆ 1.7505e9   ┆ data      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1045886 ┆ 1.7505e9   ┆ data      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1045887 ┆ 1.7505e9   ┆ data      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1045888 ┆ 1.7505e9   ┆ data      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### [oscore-schc-p2_cbor_dns_message_b64.wpan.coap.csv](data/oscore-schc-p2_cbor_dns_message_b64.wpan.coap.csv)

shape: (1_048_840, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ frame.num ┆ frame.tim ┆ frame.pro ┆ dtls.reco ┆ … ┆ oscore.op ┆ oscore.op ┆ oscore.op ┆ oscore.o │
│ ber       ┆ e_epoch   ┆ tocols    ┆ rd.conten ┆   ┆ t.ctype   ┆ t.block_n ┆ t.block_m ┆ pt.block │
│ ---       ┆ ---       ┆ ---       ┆ t_type    ┆   ┆ ---       ┆ umber     ┆ flag      ┆ _size    │
│ i64       ┆ f64       ┆ str       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 1.7504e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 1.7504e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ 1.7504e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ 1.7504e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ 1.7504e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 1048836   ┆ 1.7505e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1048837   ┆ 1.7505e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1048838   ┆ 1.7505e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1048839   ┆ 1.7505e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1048840   ┆ 1.7505e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## ❌ Error in oscore-schc-p2_json_dns_cbor_b64.training.csv.gz

Number of Non-App frames 2278

### Broken table

shape: (1_014_185, 5)
┌─────────┬──────────────┬──────────────────┬─────────────┬─────────────────────────────────┐
│         ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload                     │
│ ---     ┆ ---          ┆ ---              ┆ ---         ┆ ---                             │
│ i64     ┆ i64          ┆ f64              ┆ str         ┆ str                             │
╞═════════╪══════════════╪══════════════════╪═════════════╪═════════════════════════════════╡
│ 0       ┆ 1            ┆ 1.7503e9         ┆ dns         ┆ 0158c0e1813f840360db0d91e01347… │
│ 1       ┆ 2            ┆ 1.7503e9         ┆ dns         ┆ 01d8c0e1813f9ae1c57e62c3b086d5… │
│ 2       ┆ 3            ┆ 1.7503e9         ┆ data        ┆ 17002983e8341ac880fc6fd4689a16… │
│ 3       ┆ 4            ┆ 1.7503e9         ┆ data        ┆ 1739d50b16d75ccde53cf0e613d7ed… │
│ 4       ┆ 5            ┆ 1.7503e9         ┆ data        ┆ 01cc1f41a0d6589ac49e7ae8ec044e… │
│ …       ┆ …            ┆ …                ┆ …           ┆ …                               │
│ 1014180 ┆ 1016462      ┆ 1.7504e9         ┆ data        ┆ 01cdc8435933bdedca6f53ec48365e… │
│ 1014181 ┆ 1016463      ┆ 1.7504e9         ┆ data        ┆ 0143fcc0f91eac1ac87cf7e9d080c2… │
│ 1014182 ┆ 1016464      ┆ 1.7504e9         ┆ data        ┆ 01c3fcc0f91ea3be23e78402acda8e… │
│ 1014183 ┆ 1016465      ┆ 1.7504e9         ┆ data        ┆ 014f6ee46015cc1ac880713a0cabbd… │
│ 1014184 ┆ 1016466      ┆ 1.7504e9         ┆ data        ┆ 01cf6ee46015c1dc6cd5e893940370… │
└─────────┴──────────────┴──────────────────┴─────────────┴─────────────────────────────────┘

### Duplicate frame numbers

shape: (0, 5)
┌─────┬──────────────┬──────────────────┬─────────────┬─────────────┐
│     ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload │
│ --- ┆ ---          ┆ ---              ┆ ---         ┆ ---         │
│ i64 ┆ i64          ┆ f64              ┆ str         ┆ str         │
╞═════╪══════════════╪══════════════════╪═════════════╪═════════════╡
└─────┴──────────────┴──────────────────┴─────────────┴─────────────┘

### Expected App frames [1011907]

shape: (1_014_188, 1)
┌───────────┐
│ frame.exp │
│ ---       │
│ i64       │
╞═══════════╡
│ 1         │
│ 2         │
│ 3         │
│ 4         │
│ 5         │
│ …         │
│ 1016462   │
│ 1016463   │
│ 1016464   │
│ 1016465   │
│ 1016466   │
└───────────┘

### Different frame numbers

shape: (3, 1)
┌────────┐
│ diff   │
│ ---    │
│ i64    │
╞════════╡
│ 891924 │
│ 891925 │
│ 891926 │
└────────┘

### Non-App frames

shape: (0, 5)
┌─────┬──────────────┬──────────────────┬─────────────┬─────────────┐
│     ┆ frame.number ┆ frame.time_epoch ┆ client.type ┆ eth.payload │
│ --- ┆ ---          ┆ ---              ┆ ---         ┆ ---         │
│ i64 ┆ i64          ┆ f64              ┆ str         ┆ str         │
╞═════╪══════════════╪══════════════════╪═════════════╪═════════════╡
└─────┴──────────────┴──────────────────┴─────────────┴─────────────┘

shape: (2_278, 1)
┌────────────────┐
│ non_app_frames │
│ ---            │
│ i64            │
╞════════════════╡
│ 162            │
│ 164            │
│ 294            │
│ 296            │
│ 564            │
│ …              │
│ 1009275        │
│ 1012141        │
│ 1012143        │
│ 1013874        │
│ 1013876        │
└────────────────┘

### [oscore-schc-p2_json_dns_cbor_b64.merged.csv.gz](data/oscore-schc-p2_json_dns_cbor_b64.merged.csv.gz)

shape: (1_014_188, 54)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│         ┆ client.coa ┆ client.ty ┆ client.dn ┆ … ┆ upstream. ┆ upstream. ┆ upstream. ┆ upstream. │
│ ---     ┆ p.response ┆ pe        ┆ s.qry.nam ┆   ┆ oscore.op ┆ oscore.op ┆ oscore.op ┆ oscore.op │
│ i64     ┆ .recv_time ┆ ---       ┆ e         ┆   ┆ t.ctype   ┆ t.block_n ┆ t.block_m ┆ t.block_s │
│         ┆ …          ┆ str       ┆ ---       ┆   ┆ ---       ┆ umb…      ┆ fla…      ┆ ize       │
│         ┆ ---        ┆           ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│         ┆ f64        ┆           ┆           ┆   ┆           ┆ str       ┆ str       ┆ str       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0       ┆ 1.7503e9   ┆ dns       ┆ mc.yandex ┆ … ┆ Unknown   ┆ 0         ┆ 0         ┆ 2         │
│         ┆            ┆           ┆ .com.     ┆   ┆ Type 53   ┆           ┆           ┆           │
│ 1       ┆ 1.7503e9   ┆ dns       ┆ mc.yandex ┆ … ┆ Unknown   ┆ null      ┆ null      ┆ null      │
│         ┆            ┆           ┆ .com.     ┆   ┆ Type 53   ┆           ┆           ┆           │
│ 2       ┆ 1.7503e9   ┆ data      ┆ null      ┆ … ┆ applicati ┆ 0         ┆ 1         ┆ 2         │
│         ┆            ┆           ┆           ┆   ┆ on/json   ┆           ┆           ┆           │
│ 3       ┆ 1.7503e9   ┆ data      ┆ null      ┆ … ┆ applicati ┆ 0         ┆ 1         ┆ 2         │
│         ┆            ┆           ┆           ┆   ┆ on/json   ┆           ┆           ┆           │
│ 4       ┆ 1.7503e9   ┆ data      ┆ null      ┆ … ┆ null      ┆ 0         ┆ 1         ┆ 2         │
│ …       ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 1014183 ┆ 1.7504e9   ┆ data      ┆ null      ┆ … ┆ applicati ┆ 1         ┆ 1         ┆ 2         │
│         ┆            ┆           ┆           ┆   ┆ on/json   ┆           ┆           ┆           │
│ 1014184 ┆ 1.7504e9   ┆ data      ┆ null      ┆ … ┆ applicati ┆ 2         ┆ 0         ┆ 2         │
│         ┆            ┆           ┆           ┆   ┆ on/json   ┆           ┆           ┆           │
│ 1014185 ┆ 1.7504e9   ┆ data      ┆ null      ┆ … ┆ applicati ┆ 2         ┆ 1         ┆ 2         │
│         ┆            ┆           ┆           ┆   ┆ on/json   ┆           ┆           ┆           │
│ 1014186 ┆ 1.7504e9   ┆ data      ┆ null      ┆ … ┆ applicati ┆ 3         ┆ 0         ┆ 2         │
│         ┆            ┆           ┆           ┆   ┆ on/json   ┆           ┆           ┆           │
│ 1014187 ┆ 1.7504e9   ┆ data      ┆ null      ┆ … ┆ applicati ┆ 3         ┆ 1         ┆ 2         │
│         ┆            ┆           ┆           ┆   ┆ on/json   ┆           ┆           ┆           │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### [oscore-schc-p2_json_dns_cbor_b64.wpan.coap.csv](data/oscore-schc-p2_json_dns_cbor_b64.wpan.coap.csv)

shape: (1_016_466, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ frame.num ┆ frame.tim ┆ frame.pro ┆ dtls.reco ┆ … ┆ oscore.op ┆ oscore.op ┆ oscore.op ┆ oscore.o │
│ ber       ┆ e_epoch   ┆ tocols    ┆ rd.conten ┆   ┆ t.ctype   ┆ t.block_n ┆ t.block_m ┆ pt.block │
│ ---       ┆ ---       ┆ ---       ┆ t_type    ┆   ┆ ---       ┆ umber     ┆ flag      ┆ _size    │
│ i64       ┆ f64       ┆ str       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 1.7503e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 1.7503e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ 1.7503e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ 1.7503e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ 1.7503e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 1016462   ┆ 1.7504e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1016463   ┆ 1.7504e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1016464   ┆ 1.7504e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1016465   ┆ 1.7504e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1016466   ┆ 1.7504e9  ┆ raw:ipv6: ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ udp:coap: ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ data:osco ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re:…      ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## ✅ oscore-schc-p1_cbor_dns_cbor.training.csv.gz OK

## ✅ oscore-base-schc-p1_cbor_dns_cbor.training.csv.gz OK

## ✅ coaps-schc-d2_json_dns_message.training.csv.gz OK

## ✅ oscore-base-schc-p1_cbor_dns_message.training.csv.gz OK

## ✅ oscore-schc-p1_cbor_dns_message.training.csv.gz OK

## ✅ coaps-schc-p1_cbor_dns_cbor.training.csv.gz OK

## ✅ oscore-base-schc-p1_json_dns_cbor.training.csv.gz OK

## ✅ oscore-schc-p1_json_dns_cbor.training.csv.gz OK

## ✅ oscore-schc-p2_json_dns_message_b64.training.csv.gz OK

## ✅ coaps-schc-p1_cbor_dns_message.training.csv.gz OK

## ✅ oscore-base-schc-p2-min-rules_cbor_dns_cbor.training.csv.gz OK

## ✅ oscore-schc-p1_json_dns_message.training.csv.gz OK

## ✅ coaps-schc-p1_json_dns_cbor.training.csv.gz OK

## ✅ oscore-base-schc-p1_json_dns_message.training.csv.gz OK

## ✅ oscore-schc-p2_cbor_dns_cbor.training.csv.gz OK

## ✅ coaps-schc-p1_json_dns_message.training.csv.gz OK

## ✅ oscore-base-schc-p2-min-rules_cbor_dns_message.training.csv.gz OK

## ✅ coaps-schc-p2_cbor_dns_cbor.training.csv.gz OK

## ✅ oscore-schc-p2_cbor_dns_message.training.csv.gz OK

## ✅ oscore-base-schc-p2-min-rules_json_dns_cbor.training.csv.gz OK

## ✅ coaps-schc-p2_cbor_dns_message.training.csv.gz OK

## ✅ coaps-schc-p2_json_dns_cbor.training.csv.gz OK

## ✅ oscore-base-schc-p2_cbor_dns_cbor.training.csv.gz OK

## ✅ oscore-base-schc-p2-min-rules_json_dns_message.training.csv.gz OK

## ✅ oscore-schc-p2_json_dns_cbor.training.csv.gz OK

## ✅ coaps-schc-p2_json_dns_message.training.csv.gz OK

## ✅ oscore-schc-p2_json_dns_message.training.csv.gz OK

## ✅ oscore-base-schc-p2_cbor_dns_message.training.csv.gz OK

## ✅ oscore-base-schc-p2_json_dns_cbor.training.csv.gz OK

## ✅ oscore-base-schc-p2_json_dns_message.training.csv.gz OK